####============================###
##      Nordix - Yggdrasil      # #
##          Autostart            ┃
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
##
#
## Source
source = ~/.config/nordix/yggdrasil/settings/nordix-defaults.conf

exec-once = systemctl --user start hyprpolkitagent &

exec-once = /usr/lib/nordix/yggdrasil/bin/nordix-wallpaper-loop.sh &

exec-once = hyprctl setcursor $system_cursor $cursor_size &

## Wallpaper
exec-once = mako &
exec-once = nm-applet --indicator &
exec-once = fcitx5 -d &
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown" &
exec-once = wl-clip-persist --clipboard regular &

## Desktop & Shell
exec-once = /usr/lib/nordix/yggdrasil/bin/autostart.sh &
exec-once = $system_bar &

## Shotdown command
exec-shutdown = sync
exec-shutdown = rm -r /tmp
