#!/usr/bin/env python3
##=========================================================##
 # SPDX-License-Identifier: GPL-3.0-or-later               #
 # Copyright (c) 2025 Jimmy Källhagen                      #
 # Part of Yggdrasil - Nordix desktop environment          #
##=========================================================##

"""Nordix Binds Settings GUI
A graphical settings panel for Hyprland keybind behavior configuration
Handles: mouse, workspace switching, focus methods, group lock, drag threshold"""

import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, Gio, GLib
import subprocess
import re
import shutil
from pathlib import Path


# =============================================
# DEFAULT SETTINGS
# =============================================
DEFAULT_SETTINGS = {
    'pass_mouse_when_bound': False,
    'workspace_back_and_forth': False,
    'hide_special_on_workspace_change': True,
    'allow_workspace_cycles': True,
    'workspace_center_on': 1,
    'focus_preferred_method': 0,
    'ignore_group_lock': False,
    'movefocus_cycles_fullscreen': False,
    'movefocus_cycles_groupfirst': False,
    'disable_keybind_grabbing': False,
    'window_direction_monitor_fallback': False,
    'allow_pin_fullscreen': False,
    'drag_threshold': 0,
}


# =============================================
# FILE PATH
# =============================================
CONFIG_PATH = Path.home() / ".config" / "nordix" / "yggdrasil" / "settings" / "Yggdrasil-binds.conf"


# =============================================
# SETTINGS HANDLER
# =============================================
class BindsSettings:
    """Handles reading and writing of nordix-binds.conf"""

    def __init__(self):
        self.settings = DEFAULT_SETTINGS.copy()
        self.load_config()

    def load_config(self):
        """Read current settings from config file"""
        if not CONFIG_PATH.exists():
            print(f"Config not found: {CONFIG_PATH}, using defaults")
            return

        try:
            content = CONFIG_PATH.read_text()

            in_binds = False
            brace_depth = 0

            for line in content.split('\n'):
                stripped = line.strip()

                if stripped.startswith('# ') or not stripped:
                    continue

                if re.match(r'^binds\s*\{', stripped):
                    in_binds = True
                    brace_depth = 1
                    continue

                if '{' in stripped:
                    brace_depth += stripped.count('{')
                if '}' in stripped:
                    brace_depth -= stripped.count('}')
                    if brace_depth <= 0:
                        in_binds = False
                        brace_depth = 0
                    continue

                if not in_binds:
                    continue

                if '=' in stripped:
                    parts = stripped.split('=', 1)
                    if len(parts) == 2:
                        key = parts[0].strip()
                        value = parts[1].strip()

                        if '# ' in value:
                            value = value.split('# ')[0].strip()

                        if key in self.settings:
                            current_type = type(self.settings[key])
                            try:
                                if current_type == bool:
                                    self.settings[key] = value.lower() == 'true'
                                elif current_type == int:
                                    self.settings[key] = int(value)
                                elif current_type == float:
                                    self.settings[key] = float(value)
                                else:
                                    self.settings[key] = value
                            except ValueError:
                                pass

        except Exception as e:
            print(f"Error loading config: {e}")

    def generate_config(self):
        """Generate config file content"""
        s = self.settings

        def b(val):
            return 'true' if val else 'false'

        config = f'''
##=============================================##
 #        Yggdrasil's -  Binds Settings        #
 #          Hyprland - Configuration           #
##=============================================##
 # * Generated by Nordix Binds GUI             #
##=============================================###
binds {{

##======================##
 #     MOUSE & DRAG     #
##======================##

# Don't pass mouse events to apps when a keybind is triggered (bool)
pass_mouse_when_bound = {b(s['pass_mouse_when_bound'])}

# Movement threshold in pixels for window dragging, 0 = grab on mousedown (int)
drag_threshold = {s['drag_threshold']}


##======================##
 #  WORKSPACE BEHAVIOR  #
##======================##

# Switch to previous workspace when pressing current workspace key (bool)
workspace_back_and_forth = {b(s['workspace_back_and_forth'])}

# Hide special workspace when changing active workspace (bool)
hide_special_on_workspace_change = {b(s['hide_special_on_workspace_change'])}

# Allow workspace cycles by remembering previous workspace (bool)
allow_workspace_cycles = {b(s['allow_workspace_cycles'])}

# Center cursor on workspace (0) or last active window (1) when switching (int)
workspace_center_on = {s['workspace_center_on']}


##======================##
 #    FOCUS BEHAVIOR    #
##======================##

# Focus method: 0 = history (recent priority), 1 = length (longer shared edges) (int)
focus_preferred_method = {s['focus_preferred_method']}

# Cycle fullscreen when using movefocus on a fullscreen window (bool)
movefocus_cycles_fullscreen = {b(s['movefocus_cycles_fullscreen'])}

# Cycle group windows first before moving to other windows (bool)
movefocus_cycles_groupfirst = {b(s['movefocus_cycles_groupfirst'])}

# Move window/focus to next monitor when reaching monitor edge (bool)
window_direction_monitor_fallback = {b(s['window_direction_monitor_fallback'])}


##======================##
 #     GROUP & LOCK     #
##======================##

# Ignore group lock for move dispatchers (bool)
ignore_group_lock = {b(s['ignore_group_lock'])}

# Allow fullscreen on pinned windows (bool)
allow_pin_fullscreen = {b(s['allow_pin_fullscreen'])}


##======================##
 #   KEYBIND CONTROL    #
##======================##

# Prevent apps (e.g. VMs) from disabling keybinds (bool)
disable_keybind_grabbing = {b(s['disable_keybind_grabbing'])}


}}
'''
        return config

    def save_config(self):
        """Save configuration to file"""
        try:
            CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)

            if CONFIG_PATH.exists():
                backup = CONFIG_PATH.with_suffix('.conf.backup')
                shutil.copy2(CONFIG_PATH, backup)

            CONFIG_PATH.write_text(self.generate_config())
            return True
        except Exception as e:
            print(f"Error saving config: {e}")
            return False

    def reload_hyprland(self):
        """Reload Hyprland configuration"""
        try:
            subprocess.run(['hyprctl', 'reload'], check=True)
            return True
        except Exception as e:
            print(f"Error reloading Hyprland: {e}")
            return False

    def reset_to_defaults(self):
        """Reset all settings to defaults"""
        self.settings = DEFAULT_SETTINGS.copy()


# =============================================
# WIDGET CLASSES
# =============================================
class SliderRow(Adw.ActionRow):
    """A row with slider for numeric values"""

    def __init__(self, title, subtitle, min_val, max_val, step, value, callback, digits=0):
        super().__init__()
        self.set_title(title)
        self.set_subtitle(subtitle)

        self.callback = callback

        self.adjustment = Gtk.Adjustment(
            value=value,
            lower=min_val,
            upper=max_val,
            step_increment=step,
            page_increment=step * 10
        )

        self.scale = Gtk.Scale(
            orientation=Gtk.Orientation.HORIZONTAL,
            adjustment=self.adjustment,
            draw_value=True,
            digits=digits,
            hexpand=True
        )
        self.scale.set_size_request(200, -1)
        self.scale.connect('value-changed', self._on_value_changed)

        self.add_suffix(self.scale)

    def _on_value_changed(self, scale):
        self.callback(scale.get_value())

    def set_value(self, value):
        self.adjustment.set_value(value)


class SwitchRow(Adw.ActionRow):
    """A row with switch for boolean values"""

    def __init__(self, title, subtitle, active, callback):
        super().__init__()
        self.set_title(title)
        self.set_subtitle(subtitle)
        self.set_activatable(True)

        self.callback = callback

        self.switch = Gtk.Switch(valign=Gtk.Align.CENTER)
        self.switch.set_active(active)
        self.switch.connect('notify::active', self._on_toggled)

        self.add_suffix(self.switch)
        self.set_activatable_widget(self.switch)

    def _on_toggled(self, switch, _):
        self.callback(switch.get_active())

    def set_active(self, active):
        self.switch.set_active(active)


class DropdownRow(Adw.ActionRow):
    """A row with dropdown for selecting from a list of options"""

    def __init__(self, title, subtitle, options, current_value, callback):
        super().__init__()
        self.set_title(title)
        self.set_subtitle(subtitle)

        self.callback = callback
        self.option_values = [opt['value'] for opt in options]

        string_list = Gtk.StringList()
        current_index = 0

        for i, opt in enumerate(options):
            string_list.append(opt['name'])
            if opt['value'] == current_value:
                current_index = i

        self.dropdown = Gtk.DropDown(model=string_list)
        self.dropdown.set_selected(current_index)
        self.dropdown.connect('notify::selected', self._on_selected)

        self.add_suffix(self.dropdown)

    def _on_selected(self, dropdown, _):
        selected = dropdown.get_selected()
        if selected < len(self.option_values):
            self.callback(self.option_values[selected])

    def set_value(self, value):
        if value in self.option_values:
            index = self.option_values.index(value)
            self.dropdown.set_selected(index)


# =============================================
# MAIN WINDOW
# =============================================
class NordixBindsWindow(Adw.ApplicationWindow):
    """Main window for binds settings"""

    def __init__(self, app):
        super().__init__(application=app, title="Yggdrasil Binds Settings")
        self.set_default_size(550, 700)

        self.settings = BindsSettings()
        self.widgets = {}

        self.setup_ui()

    def setup_ui(self):
        # Main container
        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)

        # Header bar
        header = Adw.HeaderBar()

        apply_btn = Gtk.Button(label="Apply")
        apply_btn.add_css_class("suggested-action")
        apply_btn.connect("clicked", self.on_apply)
        header.pack_end(apply_btn)

        reset_btn = Gtk.Button(label="Reset to Default")
        reset_btn.connect("clicked", self.on_reset)
        header.pack_start(reset_btn)

        main_box.append(header)

        # Scrollable content
        scrolled = Gtk.ScrolledWindow(vexpand=True)
        scrolled.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)

        content = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        content.set_margin_top(12)
        content.set_margin_bottom(12)
        content.set_margin_start(12)
        content.set_margin_end(12)

        # =========================================
        # MOUSE & DRAG SECTION
        # =========================================
        mouse_group = Adw.PreferencesGroup(
            title="Mouse and Drag",
            description="Mouse behavior when keybinds are active"
        )

        self.widgets['pass_mouse_when_bound'] = SwitchRow(
            "Pass Mouse When Bound",
            "Pass mouse events to apps even when a keybind is triggered",
            self.settings.settings['pass_mouse_when_bound'],
            lambda v: self.on_value_changed('pass_mouse_when_bound', v)
        )
        mouse_group.add(self.widgets['pass_mouse_when_bound'])

        self.widgets['drag_threshold'] = SliderRow(
            "Drag Threshold",
            "Pixel movement before drag starts, 0 = instant grab [0 - 20]",
            0, 20, 1, self.settings.settings['drag_threshold'],
            lambda v: self.on_value_changed('drag_threshold', int(v))
        )
        mouse_group.add(self.widgets['drag_threshold'])

        content.append(mouse_group)

        # =========================================
        # WORKSPACE BEHAVIOR SECTION
        # =========================================
        workspace_group = Adw.PreferencesGroup(
            title="Workspace Behavior",
            description="How workspace switching behaves"
        )

        self.widgets['workspace_back_and_forth'] = SwitchRow(
            "Back and Forth",
            "Pressing current workspace key switches to previous workspace",
            self.settings.settings['workspace_back_and_forth'],
            lambda v: self.on_value_changed('workspace_back_and_forth', v)
        )
        workspace_group.add(self.widgets['workspace_back_and_forth'])

        self.widgets['hide_special_on_workspace_change'] = SwitchRow(
            "Hide Special on Change",
            "Hide special workspace when switching workspaces",
            self.settings.settings['hide_special_on_workspace_change'],
            lambda v: self.on_value_changed('hide_special_on_workspace_change', v)
        )
        workspace_group.add(self.widgets['hide_special_on_workspace_change'])

        self.widgets['allow_workspace_cycles'] = SwitchRow(
            "Allow Workspace Cycles",
            "Workspaces remember previous workspace for cycling",
            self.settings.settings['allow_workspace_cycles'],
            lambda v: self.on_value_changed('allow_workspace_cycles', v)
        )
        workspace_group.add(self.widgets['allow_workspace_cycles'])

        self.widgets['workspace_center_on'] = DropdownRow(
            "Center Cursor On",
            "Where to center cursor when switching workspaces",
            [
                {'value': 0, 'name': 'Workspace center'},
                {'value': 1, 'name': 'Last active window'},
            ],
            self.settings.settings['workspace_center_on'],
            lambda v: self.on_value_changed('workspace_center_on', v)
        )
        workspace_group.add(self.widgets['workspace_center_on'])

        content.append(workspace_group)

        # =========================================
        # FOCUS BEHAVIOR SECTION
        # =========================================
        focus_group = Adw.PreferencesGroup(
            title="Focus Behavior",
            description="How window focus is determined"
        )

        self.widgets['focus_preferred_method'] = DropdownRow(
            "Focus Method",
            "How focus target is chosen when moving in a direction",
            [
                {'value': 0, 'name': 'History (recent windows first)'},
                {'value': 1, 'name': 'Length (longer shared edges first)'},
            ],
            self.settings.settings['focus_preferred_method'],
            lambda v: self.on_value_changed('focus_preferred_method', v)
        )
        focus_group.add(self.widgets['focus_preferred_method'])

        self.widgets['movefocus_cycles_fullscreen'] = SwitchRow(
            "Cycle Fullscreen",
            "Movefocus cycles fullscreen state instead of direction",
            self.settings.settings['movefocus_cycles_fullscreen'],
            lambda v: self.on_value_changed('movefocus_cycles_fullscreen', v)
        )
        focus_group.add(self.widgets['movefocus_cycles_fullscreen'])

        self.widgets['movefocus_cycles_groupfirst'] = SwitchRow(
            "Cycle Group First",
            "Cycle through group windows before moving to other windows",
            self.settings.settings['movefocus_cycles_groupfirst'],
            lambda v: self.on_value_changed('movefocus_cycles_groupfirst', v)
        )
        focus_group.add(self.widgets['movefocus_cycles_groupfirst'])

        self.widgets['window_direction_monitor_fallback'] = SwitchRow(
            "Monitor Fallback",
            "Move focus/window to next monitor when reaching edge",
            self.settings.settings['window_direction_monitor_fallback'],
            lambda v: self.on_value_changed('window_direction_monitor_fallback', v)
        )
        focus_group.add(self.widgets['window_direction_monitor_fallback'])

        content.append(focus_group)

        # =========================================
        # GROUP & LOCK SECTION
        # =========================================
        group_section = Adw.PreferencesGroup(
            title="Group and Lock",
            description="Group lock and pinning behavior"
        )

        self.widgets['ignore_group_lock'] = SwitchRow(
            "Ignore Group Lock",
            "Move dispatchers ignore group lock state",
            self.settings.settings['ignore_group_lock'],
            lambda v: self.on_value_changed('ignore_group_lock', v)
        )
        group_section.add(self.widgets['ignore_group_lock'])

        self.widgets['allow_pin_fullscreen'] = SwitchRow(
            "Allow Pin Fullscreen",
            "Allow fullscreen on pinned windows and restore pin after",
            self.settings.settings['allow_pin_fullscreen'],
            lambda v: self.on_value_changed('allow_pin_fullscreen', v)
        )
        group_section.add(self.widgets['allow_pin_fullscreen'])

        content.append(group_section)

        # =========================================
        # KEYBIND CONTROL SECTION
        # =========================================
        keybind_group = Adw.PreferencesGroup(
            title="Keybind Control",
            description="How apps interact with keybinds"
        )

        self.widgets['disable_keybind_grabbing'] = SwitchRow(
            "Disable Keybind Grabbing",
            "Prevent apps (e.g. VMs) from requesting keybinds to be disabled",
            self.settings.settings['disable_keybind_grabbing'],
            lambda v: self.on_value_changed('disable_keybind_grabbing', v)
        )
        keybind_group.add(self.widgets['disable_keybind_grabbing'])

        content.append(keybind_group)

        scrolled.set_child(content)
        main_box.append(scrolled)

        # Status bar
        self.status_bar = Gtk.Label(label="Ready")
        self.status_bar.add_css_class("dim-label")
        self.status_bar.set_margin_top(6)
        self.status_bar.set_margin_bottom(6)
        main_box.append(self.status_bar)

        self.set_content(main_box)

    def on_value_changed(self, key, value):
        """Update a setting"""
        self.settings.settings[key] = value
        self.status_bar.set_text(f"Changed: {key} = {value}")

    def on_apply(self, button):
        """Save and apply changes"""
        if self.settings.save_config():
            if self.settings.reload_hyprland():
                self.status_bar.set_text("Saved and applied successfully!")
            else:
                self.status_bar.set_text("Saved (could not reload Hyprland)")
        else:
            self.status_bar.set_text("Error saving configuration!")

    def on_reset(self, button):
        """Reset to default values"""
        self.settings.reset_to_defaults()
        self.refresh_ui()
        self.status_bar.set_text("Reset to Nordix defaults — click Apply to save")

    def refresh_ui(self):
        """Update all widgets with current values"""
        s = self.settings.settings

        for key, widget in self.widgets.items():
            if key in s:
                if isinstance(widget, SliderRow):
                    widget.set_value(s[key])
                elif isinstance(widget, SwitchRow):
                    widget.set_active(s[key])
                elif isinstance(widget, DropdownRow):
                    widget.set_value(s[key])


# =============================================
# APPLICATION
# =============================================
class NordixBindsApp(Adw.Application):
    """Main application"""

    def __init__(self):
        super().__init__(
            application_id='com.Nordix.Settings.Binds',
            flags=Gio.ApplicationFlags.FLAGS_NONE
        )

    def do_activate(self):
        win = NordixBindsWindow(self)
        win.present()


def main():
    app = NordixBindsApp()
    return app.run(None)


if __name__ == "__main__":
    main()
