#!/usr/bin/env python3
##=========================================================##
 # SPDX-License-Identifier: GPL-3.0-or-later               #
 # Copyright (c) 2025 Jimmy Källhagen                      #
 # Part of Yggdrasil - Nordix desktop environment          #
##=========================================================##

"""Yggdrasil System Settings - Input
Generated by Nordix GUI Manager
Config: ~/nordix/hyprland/config/nordix-settings-input.conf"""



import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, Gio, GLib
import subprocess
from pathlib import Path
import sys



# CONFIGURATION


CONFIG_PATH = Path.home() / ".config/nordix/yggdrasil/settings/Yggdrasil-input.conf"
APP_TITLE = "Yggdrasil Input Settings"
WINDOW_WIDTH = 550
WINDOW_HEIGHT = 900



# OPTIONS


KB_LAYOUT_OPTIONS = [
    ('Albanian', 'al'),
    ('Amharic', 'et'),
    ('Armenian', 'am'),
    ('Arabic', 'ara'),
    ('Arabic (Egypt)', 'eg'),
    ('Arabic (Iraq)', 'iq'),
    ('Arabic (Morocco)', 'ma'),
    ('Arabic (Syria)', 'sy'),
    ('Azerbaijani', 'az'),
    ('Bambara', 'ml'),
    ('Bangla', 'bd'),
    ('Belarusian', 'by'),
    ('Belgian', 'be'),
    ('Berber (Algeria, Latin)', 'dz'),
    ('Bosnian', 'ba'),
    ('Braille', 'brai'),
    ('Bulgarian', 'bg'),
    ('Burmese', 'mm'),
    ('Chinese', 'cn'),
    ('Croatian', 'hr'),
    ('Czech', 'cz'),
    ('Danish', 'dk'),
    ('Dari', 'af'),
    ('Dhivehi', 'mv'),
    ('Dutch', 'nl'),
    ('Dzongkha', 'bt'),
    ('English (Australia)', 'au'),
    ('English (Cameroon)', 'cm'),
    ('English (Ghana)', 'gh'),
    ('English (New Zealand)', 'nz'),
    ('English (Nigeria)', 'ng'),
    ('English (South Africa)', 'za'),
    ('English (UK)', 'gb'),
    ('English (US)', 'us'),
    ('Esperanto', 'epo'),
    ('Estonian', 'ee'),
    ('Faroese', 'fo'),
    ('Filipino', 'ph'),
    ('Finnish', 'fi'),
    ('French', 'fr'),
    ('French (Canada)', 'ca'),
    ('French (Democratic Republic of the Congo)', 'cd'),
    ('French (Togo)', 'tg'),
    ('Georgian', 'ge'),
    ('German', 'de'),
    ('German (Austria)', 'at'),
    ('German (Switzerland)', 'ch'),
    ('Greek', 'gr'),
    ('Hebrew', 'il'),
    ('Hungarian', 'hu'),
    ('Icelandic', 'is'),
    ('Indian', 'in'),
    ('Indonesian (Latin)', 'id'),
    ('Irish', 'ie'),
    ('Italian', 'it'),
    ('Japanese', 'jp'),
    ('Kazakh', 'kz'),
    ('Khmer (Cambodia)', 'kh'),
    ('Korean', 'kr'),
    ('Kyrgyz', 'kg'),
    ('Lao', 'la'),
    ('Latvian', 'lv'),
    ('Lithuanian', 'lt'),
    ('Macedonian', 'mk'),
    ('Malay (Jawi, Arabic Keyboard)', 'my'),
    ('Maltese', 'mt'),
    ('Moldavian', 'md'),
    ('Mongolian', 'mn'),
    ('Montenegrin', 'me'),
    ('Nepali', 'np'),
    ('N Ko (AZERTY)', 'gn'),
    ('Norwegian', 'no'),
    ('Persian', 'ir'),
    ('Polish', 'pl'),
    ('Portuguese', 'pt'),
    ('Portuguese (Brazil)', 'br'),
    ('Romanian', 'ro'),
    ('Russian', 'ru'),
    ('Serbian', 'rs'),
    ('Sinhala (phonetic)', 'lk'),
    ('Slovak', 'sk'),
    ('Slovenian', 'si'),
    ('Spanish', 'es'),
    ('Spanish (Latin American)', 'latam'),
    ('Swahili (Kenya)', 'ke'),
    ('Swahili (Tanzania)', 'tz'),
    ('Swedish', 'se'),
    ('Taiwanese', 'tw'),
    ('Tajik', 'tj'),
    ('Thai', 'th'),
    ('Tswana', 'bw'),
    ('Turkmen', 'tm'),
    ('Turkish', 'tr'),
    ('Ukrainian', 'ua'),
    ('Urdu (Pakistan)', 'pk'),
    ('Uzbek', 'uz'),
    ('Vietnamese', 'vn'),
    ('Wolof', 'sn'),
]

KB_VARIANT_OPTIONS = [
    ('Albanian Plisi', 'plisi # Albanian'),
    ('Albanian Veqilharxhi', 'veqilharxhi # Albanian'),
    ('Armenian phonetic', 'phonetic # Armenian'),
    ('Armenian alt. phonetic', 'phonetic-alt # Armenian'),
    ('Armenian eastern', 'eastern # Armenian'),
    ('Armenian alt. eastern', 'eastern-alt # Armenian'),
    ('Armenian western', 'western # Armenian'),
    ('Arabic Eastern Arabic numerals', 'digits # Arabic'),
    ('Arabic AZERTY', 'azerty # Arabic'),
    ('Arabic AZERTY, Eastern Arabic numerals', 'azerty_digits # Arabic'),
    ('Arabic Buckwalter', 'buckwalter # Arabic'),
    ('Arabic Macintosh', 'mac # Arabic'),
    ('Arabic Macintosh, phonetic', 'mac-phonetic # Arabic'),
    ('Arabic OLPC', 'olpc # Arabic'),
    ('Kurdish Iraq, Latin Q', 'ku # Ku I'),
    ('Kurdish Iraq, Latin Alt-Q', 'ku_alt # Ku I'),
    ('Kurdish Iraq, F', 'ku_f # Ku I'),
    ('Kurdish Iraq, Arabic-Latin', 'ku_ara # Ku I'),
    ('Berber Morocco, Tifinagh', 'tifinagh # Berber Morocco'),
    ('Berber Morocco, Tifinagh alt.', 'tifinagh-alt # Berber Morocco'),
    ('Berber Morocco, Tifinagh phonetic, alt.', 'tifinagh-alt-phonetic # Berber Morocco'),
    ('Berber Morocco, Tifinagh extended', 'tifinagh-extended # Berber Morocco'),
    ('Berber Morocco, Tifinagh phonetic', 'tifinagh-phonetic # Berber Morocco'),
    ('Berber Morocco, Tifinagh extended phonetic', 'tifinagh-extended-phonetic # Berber Morocco'),
    ('French Morocco', 'french # French Morocco'),
    ('Tarifit', 'rif'),
    ('Syriac', 'syc'),
    ('Syriac phonetic', 'syc_phonetic'),
    ('Kurdish Syria, Latin Q', 'ku'),
    ('Kurdish Syria, Latin Alt-Q', 'ku_alt'),
    ('Kurdish Syria, F', 'ku_f'),
    ('Azerbaijani Cyrillic', 'cyrillic # Azerbaijani'),
    ('French Mali, alt.', 'fr-oss # French Mali'),
    ('English Mali, US, Macintosh', 'us-mac # English Mali'),
    ('English Mali, US, intl.', 'us-intl # English Mali'),
    ('Bangla Probhat', 'probhat # Bengal'),
    ('Belarusian legacy', 'legacy # Belarusian'),
    ('Belarusian Latin', 'latin # Belarusian'),
    ('Belarusian intl.', 'intl # Belarusian'),
    ('Belarusian phonetic', 'phonetic # Belarusian'),
    ('Russian Belarus', 'ru # Russian Belarus'),
    ('Belgian alt.', 'oss # Belgian'),
    ('Belgian Latin-9 only, alt.', 'oss_latin9 # Belgian'),
    ('Belgian ISO, alt.', 'iso-alternate # Belgian'),
    ('Belgian no dead keys', 'nodeadkeys # Belgian'),
    ('Belgian Wang 724 AZERTY', 'wang'),
    ('Berber Algeria, Tifinagh', 'ber'),
    ('Kabyle AZERTY, with dead keys', 'azerty-deadkeys # Kabyle'),
    ('Kabyle QWERTY, UK, with dead keys', 'qwerty-gb-deadkeys # Kabyle'),
    ('Kabyle QWERTY, US, with dead keys', 'qwerty-us-deadkeys # Kabyle'),
    ('Arabic Algeria', 'ar'),
    ('Bosnian with guillemets', 'alternatequotes # Bosnian'),
    ('Bosnian with Bosnian digraphs', 'unicode # Bosnian'),
    ('Bosnian US, with Bosnian digraphs', 'unicodeus # Bosnian'),
    ('Bosnian US', 'us # Bosnian'),
    ('Braille left-handed', 'left_hand # Braille'),
    ('Braille left-handed inverted thumb', 'left_hand_invert # Braille'),
    ('Braille right-handed', 'right_hand # Braille'),
    ('Braille right-handed inverted thumb', 'right_hand_invert # Braille'),
    ('Bulgarian traditional phonetic', 'phonetic'),
    ('Bulgarian new phonetic', 'bas_phonetic'),
    ('Bulgarian enhanced', 'bekl'),
    ('Burmese Zawgyi', 'zawgyi'),
    ('Mon', 'mnw'),
    ('Mon A1', 'mnw-a1'),
    ('Shan', 'shn'),
    ('Shan Zawgyi', 'zgt'),
    ('Hanyu Pinyin Letters with AltGr dead keys', 'altgr-pinyin'),
    ('Mongolian Bichig', 'mon_trad'),
    ('Mongolian Todo', 'mon_trad_todo'),
    ('Mongolian Xibe', 'mon_trad_xibe'),
    ('Mongolian Manchu', 'mon_trad_manchu'),
    ('Mongolian Galik', 'mon_trad_galik'),
    ('Mongolian Todo Galik', 'mon_todo_galik'),
    ('Mongolian Manchu Galik', 'mon_manchu_galik'),
    ('Tibetan', 'tib'),
    ('Tibetan with ASCII numerals', 'tib_asciinum'),
    ('Uyghur', 'ug'),
    ('Croatian with guillemets', 'alternatequotes # Croatian'),
    ('Croatian with Croatian digraphs', 'unicode # Croatian'),
    ('Croatian US, with Croatian digraphs', 'unicodeus # Croatian'),
    ('Croatian US', 'us # Croatian'),
    ('Czech extra backslash', 'bksl # Czech'),
    ('Czech QWERTY', 'qwerty # Czech'),
    ('Czech QWERTY, extra backslash', 'qwerty_bksl # Czech'),
    ('Czech QWERTZ, Windows', 'winkeys # Czech'),
    ('Czech QWERTY, Windows', 'winkeys-qwerty # Czech'),
    ('Czech QWERTY, Macintosh', 'qwerty-mac # Czech'),
    ('Czech UCW, only accented letters', 'ucw # Czech'),
    ('Czech US, Dvorak, UCW support', 'dvorak-ucw # Czech'),
    ('Russian Czechia, phonetic', 'rus'),
    ('Danish no dead keys', 'nodeadkeys # Danish '),
    ('Danish Windows', 'winkeys # Danish'),
    ('Danish Macintosh', 'mac # Danish'),
    ('Danish Macintosh, no dead keys', 'mac_nodeadkeys # Danish'),
    ('Danish Dvorak', 'dvorak # Danish'),
    ('Pashto', 'ps'),
    ('Uzbek Afghanistan', 'uz'),
    ('Dari Afghanistan, OLPC', 'fa-olpc'),
    ('Pashto Afghanistan, OLPC', 'ps-olpc'),
    ('Uzbek Afghanistan, OLPC', 'uz-olpc'),
    ('Dutch US', 'us # Dutch'),
    ('Dutch Macintosh', 'mac # Dutch'),
    ('Dutch standard', 'std # Dutch'),
    ('French Cameroon', 'french # French Cameroon'),
    ('Cameroon Multilingual QWERTY, intl.', 'qwerty # Cameroon'),
    ('Cameroon AZERTY, intl.', 'azerty # Cameroon'),
    ('Cameroon Dvorak, intl.', 'dvorak # Cameroon'),
    ('Mmuock', 'mmuock'),
    ('English Ghana, multilingual', 'generic # Englsh Ghana'),
    ('English Ghana, GILLBT', 'gillbt # English Ghana'),
    ('Akan', 'akan'),
    ('Avatime', 'avn'),
    ('Ewe', 'ewe'),
    ('Fula', 'fula'),
    ('Ga', 'ga'),
    ('Hausa Ghana', 'hausa #Hausa Ghana'),
    ('Maori', 'mao'),
    ('Hausa Nigeria', 'hausa # Hausa Nigeria'),
    ('Igbo', 'igbo'),
    ('Yoruba', 'yoruba'),
    ('English UK, extended, Windows', 'extd # English'),
    ('English UK, intl., with dead keys', 'intl # English'),
    ('English UK, Dvorak', 'dvorak # English'),
    ('English UK, Dvorak, with UK punctuation', 'dvorakukp # English'),
    ('English UK, Macintosh', 'mac # English'),
    ('English UK, Macintosh, intl.', 'mac_intl # English'),
    ('English UK, Colemak', 'colemak # English'),
    ('English UK, Colemak-DH', 'colemak_dh # # English'),
    ('Scottish Gaelic', 'gla # Scottish Gaelic'),
    ('Polish British keyboard', 'pl # Polish British keyboard'),
    ('English US, euro on 5', 'euro # English'),
    ('English US, intl., with dead keys', 'intl # English'),
    ('English US, alt. intl.', 'alt-intl # English'),
    ('English intl., with AltGr dead keys', 'altgr-intl # English'),
    ('English Macintosh', 'mac # English'),
    ('English Colemak', 'colemak # English'),
    ('English Colemak-DH', 'colemak_dh # English'),
    ('English Colemak-DH Wide', 'colemak_dh_wide # English'),
    ('English Colemak-DH Ortholinear', 'colemak_dh_ortho # English'),
    ('English Colemak-DH ISO', 'colemak_dh_iso # English'),
    ('English Colemak-DH Wide ISO', 'colemak_dh_wide_iso # English'),
    ('English Dvorak', 'dvorak # English'),
    ('English Dvorak, intl., with dead keys', 'dvorak-intl # English'),
    ('English Dvorak, alt. intl.', 'dvorak-alt-intl # English'),
    ('English Dvorak, left-handed', 'dvorak-l # English'),
    ('English Dvorak, right-handed', 'dvorak-r # English'),
    ('English classic Dvorak', 'dvorak-classic # English'),
    ('English programmer Dvorak', 'dvp # English'),
    ('English Dvorak, Macintosh', 'dvorak-mac # English'),
    ('English Norman', 'norman # English'),
    ('English US, Symbolic', 'symbolic'),
    ('English Workman', 'workman # English'),
    ('English Workman, intl., with dead keys', 'workman-intl # English'),
    ('English the divide/multiply toggle the layout', 'olpc2'),
    ('Cherokee', 'chr # Cherokee'),
    ('Hawaiian', 'haw # Hawaiian'),
    ('Russian US, phonetic', 'rus # Russain US'),
    ('Serbo-Croatian US', 'hbs # Serbo-Croatian US'),
    ('Esperanto legacy', 'legacy # Es'),
    ('Estonian no dead keys', 'nodeadkeys # Estonian'),
    ('Estonian Dvorak', 'dvorak # Estonian'),
    ('Estonian US', 'us # Estonian'),
    ('Faroese no dead keys', 'nodeadkeys # Faroese'),
    ('Filipino QWERTY, Baybayin', 'qwerty-bay # Filipino'),
    ('Filipino Capewell-Dvorak, Latin', 'capewell-dvorak # Filipino'),
    ('Filipino Capewell-Dvorak, Baybayin', 'capewell-dvorak-bay # Filipino'),
    ('Filipino Capewell-QWERF 2006, Latin', 'capewell-qwerf2k6 # Filipino'),
    ('Filipino Capewell-QWERF 2006, Baybayin', 'capewell-qwerf2k6-bay # Filipino'),
    ('Filipino Colemak, Latin', 'colemak # Filipino'),
    ('Filipino Colemak, Baybayin', 'colemak-bay # Filipino'),
    ('Filipino Dvorak, Latin', 'dvorak # Filipino'),
    ('Filipino Dvorak, Baybayin', 'dvorak-bay # Filipino'),
    ('Finnish Windows', 'winkeys # Finnish'),
    ('Finnish classic', 'classic # Finnish'),
    ('Finnish classic, no dead keys', 'nodeadkeys # Finnish'),
    ('Finnish Macintosh', 'mac # Finnish'),
    ('Northern Saami Finland', 'smi # Northern Saami Finland'),
    ('French no dead keys', 'nodeadkeys # French'),
    ('French alt.', 'oss # French'),
    ('French alt., no dead keys', 'oss_nodeadkeys # French'),
    ('French alt., Latin-9 only', 'oss_latin9 # French'),
    ('French legacy, alt.', 'latin9 # French'),
    ('French legacy, alt., no dead keys', 'latin9_nodeadkeys # French'),
    ('French AZERTY', 'azerty # French'),
    ('French AZERTY, AFNOR', 'afnor # French'),
    ('French BEPO', 'bepo # French'),
    ('French BEPO, Latin-9 only', 'bepo_latin9 # French'),
    ('French BEPO, AFNOR', 'bepo_afnor # French'),
    ('French Dvorak', 'dvorak # French'),
    ('French Ergol', 'ergol # French'),
    ('French Ergol, ISO variant', 'ergol_iso # French'),
    ('French Macintosh', 'mac # French'),
    ('French US', 'us # French US'),
    ('Breton France', 'bre # Breton France'),
    ('Occitan', 'oci # Occitan'),
    ('Georgian France, AZERTY Tskapo', 'geo # Georgian French'),
    ('French Canada, Dvorak', 'fr-dvorak # French Canadian'),
    ('French Canada, legacy', 'fr-legacy # French Canadian'),
    ('Canadian CSA', 'multix # Canadian CSA'),
    ('English Canada', 'eng # English Canada'),
    ('Inuktitut', 'ike # Inuktitut'),
    ('Georgian ergonomic', 'ergonomic # Georgia'),
    ('Georgian MESS', 'mess # Georgia'),
    ('Ossetian Georgia', 'os # Ossetian Georgia'),
    ('Russian Georgia', 'ru # Russian Georgia'),
    ('German dead acute', 'deadacute # German'),
    ('German dead grave acute', 'deadgraveacute # German'),
    ('German dead tilde', 'deadtilde # German'),
    ('German no dead keys', 'nodeadkeys # German'),
    ('German E1', 'e1 # German E1'),
    ('German E2', 'e2 # German E2'),
    ('German T3', 'T3 # German T3'),
    ('German US', 'us # German US'),
    ('German Dvorak', 'dvorak # German Dvorak'),
    ('German Macintosh', 'mac # German Machintosh'),
    ('German Macintosh, no dead keys', 'mac_nodeadkeys # German Macintosh'),
    ('German Neo 2', 'neo # German Neo 2'),
    ('German QWERTY', 'qwerty # German QWERTY'),
    ('Lower Sorbian', 'dsb # Lower Sorbian'),
    ('Lower Sorbian QWERTZ', 'dsb_qwertz 3 # Lower Sorbian'),
    ('Romanian Germany', 'ro # Russian Germany'),
    ('Romanian Germany, no dead keys', 'ro_nodeadkeys # Russian Germany'),
    ('Russian Germany, phonetic', 'ru # Russian Germany'),
    ('Turkish Germany', 'tr # Turkish Germany'),
    ('German Austria, no dead keys', 'nodeadkeys # German Austria'),
    ('German Austria, Macintosh', 'mac # German Austria'),
    ('German Switzerland, no dead keys', 'de_nodeadkeys # German Switzerland'),
    ('German Switzerland, Macintosh', 'de_mac # German Switzerland'),
    ('German Switzerland, legacy', 'legacy # German Switzerland'),
    ('French Switzerland', 'fr # French Switzerland'),
    ('French Switzerland, no dead keys', 'fr_nodeadkeys # French Switzerland'),
    ('French Switzerland, Macintosh', 'fr_mac # French Switzerland'),
    ('Greek simple', 'simple # Greek'),
    ('Greek no dead keys', 'nodeadkeys # Greek'),
    ('Greek polytonic', 'polytonic # Greek'),
    ('Hebrew SI-1452-2', 'si2 # Hebrew'),
    ('Hebrew lyx', 'lyx # Hebrew'),
    ('Hebrew phonetic', 'phonetic # Hebrew'),
    ('Hebrew Biblical, Tiro', 'biblical # Hebrew'),
    ('Hungarian standard', 'standard # Hungarian'),
    ('Hungarian no dead keys', 'nodeadkeys # Hungarian'),
    ('Hungarian QWERTY', 'qwerty # Hungarian'),
    ('Hungarian QWERTZ, 101-key, comma, dead keys', '101_qwertz_comma_dead # Hungarian'),
    ('Hungarian QWERTZ, 101-key, comma, no dead keys', '101_qwertz_comma_nodead # Hungarian'),
    ('Hungarian QWERTZ, 101-key, dot, dead keys', '101_qwertz_dot_dead # Hungarian'),
    ('Hungarian QWERTZ, 101-key, dot, no dead keys', '101_qwertz_dot_nodead # Hungarian'),
    ('Hungarian QWERTY, 101-key, comma, dead keys', '101_qwerty_comma_dead # Hungarian'),
    ('Hungarian QWERTY, 101-key, comma, no dead keys', '101_qwerty_comma_nodead # Hungarian'),
    ('Hungarian QWERTY, 101-key, dot, dead keys', '101_qwerty_dot_dead # Hungarian'),
    ('Hungarian QWERTY, 101-key, dot, no dead keys', '101_qwerty_dot_nodead # Hungarian'),
    ('Hungarian QWERTZ, 102-key, comma, dead keys', '102_qwertz_comma_dead # Hungarian'),
    ('Hungarian QWERTZ, 102-key, comma, no dead keys', '102_qwertz_comma_nodead # Hungarian'),
    ('Hungarian QWERTZ, 102-key, dot, dead keys', '102_qwertz_dot_dead # Hungarian'),
    ('Hungarian QWERTZ, 102-key, dot, no dead keys', '102_qwertz_dot_nodead # Hungarian'),
    ('Hungarian QWERTY, 102-key, comma, dead keys', '102_qwerty_comma_dead # Hungarian'),
    ('Hungarian QWERTY, 102-key, comma, no dead keys', '102_qwerty_comma_nodead # Hungarian'),
    ('Hungarian QWERTY, 102-key, dot, dead keys', '102_qwerty_dot_dead # Hungarian'),
    ('Hungarian QWERTY, 102-key, dot, no dead keys', '102_qwerty_dot_nodead # Hungarian'),
    ('Icelandic Macintosh, legacy', 'mac_legacy # Icelandic'),
    ('Icelandic Macintosh', 'mac # Icelandic'),
    ('Icelandic Dvorak', 'dvorak # Icelandic'),
    ('Swedish', 'se'),
    ('Swedish no dead keys', 'nodeadkeys # Swedish'),
    ('Swedish Dvorak', 'dvorak # Swedish'),
    ('Swedish Dvorak, A5', 'dvorak_a5 # Swedish'),
    ('Swedish Svdvorak', 'svdvorak # Swedish'),
    ('Swedish Macintosh', 'mac # Swedish'),
    ('Swedish Sami', 'smi # Swedish'),
    ('Norwegian', 'no'),
    ('Norwegian no dead keys', 'nodeadkeys # Norwegian'),
    ('Norwegian Windows', 'winkeys # Norwegian'),
    ('Norwegian Macintosh', 'mac # Norwegian'),
    ('Norwegian Sami', 'smi # Norwegian'),
    ('Norwegian Dvorak', 'dvorak # Norwegian'),
]

KB_MODEL_OPTIONS = [
    ('Generic 101-key PC', 'pc101'),
    ('Generic 102-key (intl) PC', 'pc102'),
    ('Generic 104-key PC', 'pc104'),
    ('Generic 105-key (intl) PC', 'pc105'),
    ('Generic 86-key PC', 'pc86'),
    ('Generic PC', 'pc'),
    ('Acer Aspire 5', 'acer_aspire_5'),
    ('Acer TravelMate C300', 'acer_c300'),
    ('Acer Ferrari 4000', 'acer_ferrari4k'),
    ('Apple', 'apple'),
    ('Apple Laptop', 'apple_laptop'),
    ('Asus Laptop', 'asus_laptop'),
    ('BTC 5090', 'btc5090'),
    ('BTC 5113RF Multimedia', 'btc5113rf'),
    ('BTC 5126T', 'btc5126t'),
    ('BTC 6301urf', 'btc6301urf'),
    ('BTC 9000', 'btc9000'),
    ('BTC 9000A', 'btc9000a'),
    ('BTC 9001AH', 'btc9001ah'),
    ('BTC 9019U', 'btc9019u'),
    ('BTC 9116U Mini', 'btc9116u'),
    ('Chromebook', 'chromebook'),
    ('Compaq Internet keyboard', 'compaqik'),
    ('Compaq Internet keyboard (18 keys)', 'compaqik18'),
    ('Compaq Evo N800V', 'compaq_evo_n800v'),
    ('Dell', 'dell'),
    ('Dell 101-key PC', 'dellpc101'),
    ('Dell Inspiron 6000', 'dell_inspiron_6000'),
    ('Dell Latitude', 'delllatitude'),
    ('Dell Precision M65', 'dellm65'),
    ('Dell SK-8125', 'dellsk8125'),
    ('Dell SK-8135', 'dellsk8135'),
    ('Ennyah DKB-1008', 'ennyah_dkb1008'),
    ('Everex STEPnote', 'everex_stepnote'),
    ('Fujitsu-Siemens Computers Amilo laptop', 'fscfsamilo'),
    ('Genius Comfy KB-12e', 'geniuskb12e'),
    ('Genius KB-29E', 'geniuskb29e'),
    ('Hewlett-Packard Internet keyboard', 'hpik'),
    ('Hewlett-Packard Omnibook 500 FA', 'hpi500fa'),
    ('Hewlett-Packard Omnibook 5xx', 'hpi5xx'),
    ('Hewlett-Packard Omnibook 6000', 'hpi6000'),
    ('Hewlett-Packard Omnibook XE3', 'hpxe3'),
    ('Hewlett-Packard ZT11', 'hpzt11'),
    ('Honeywell Euroboard', 'honeywell_euroboard'),
    ('IBM Rapid Access', 'rapidaccess'),
    ('IBM Rapid Access II', 'rapidaccess2'),
    ('IBM Space Saver', 'ibm_spacesaver'),
    ('IBM ThinkPad 560Z/600/600E/A22E', 'thinkpad'),
    ('IBM ThinkPad 60 series', 'thinkpad60'),
    ('IBM ThinkPad R60/T60/Z60', 'thinkpadz60'),
    ('Kinesis', 'kinesis'),
    ('Kinesis Advantage', 'kinesis_advantage'),
    ('Logitech Access Keyboard', 'logiaccess'),
    ('Logitech Cordless Desktop', 'logicda'),
    ('Logitech Cordless Desktop EX110', 'logicex110'),
    ('Logitech Cordless Desktop Pro', 'logicdp'),
    ('Logitech Cordless Desktop Pro USB', 'logicdpu'),
    ('Logitech Cordless Navigation', 'logicnav'),
    ('Logitech G15', 'logitech_g15'),
    ('Logitech Internet Navigator', 'logiik'),
    ('Logitech UltraX Cordless Media Desktop', 'logicux'),
    ('MacBook/MacBook Pro', 'macbook78'),
    ('MacBook/MacBook Pro (Intl)', 'macbook79'),
    ('Microsoft Comfort Curve Keyboard 2000', 'microsoft2000'),
    ('Microsoft Internet Keyboard', 'msik'),
    ('Microsoft Internet Keyboard Pro', 'msikpro'),
    ('Microsoft Natural', 'microsoft'),
    ('Microsoft Natural Keyboard Elite', 'microsoftelite'),
    ('Microsoft Natural Keyboard Pro', 'microsoftpro'),
    ('Microsoft Natural Pro USB', 'microsoftprousb'),
    ('Microsoft Office Keyboard', 'microsoftoffice'),
    ('Microsoft Wireless Multimedia Keyboard 1.0A', 'microsoftmult'),
    ('Memorex MX1998', 'memorex_mx1998'),
    ('Memorex MX2500 EZ-Access', 'memorex_mx2500'),
    ('Memorex MX2750', 'memorex_mx2750'),
    ('NEC SK-1300', 'necsk1300'),
    ('NEC SK-2500', 'necsk2500'),
    ('NEC SK-6200', 'necsk6200'),
    ('NEC SK-7100', 'necsk7100'),
    ('Ortek MCK-800 Multimedia Keyboard', 'ortekmck800'),
    ('PC-98xx Series', 'pc98'),
    ('Propeller Voyager KTEZ-1000', 'propellerkt'),
    ('QTronix Scorpius 98N', 'qtronixscorpius98'),
    ('Samsung SDM 4500P', 'samsungsdm4500p'),
    ('Samsung SDM 4510P', 'samsungsdm4510p'),
    ('Sony Vaio', 'sony_vaio'),
    ('Sun Type 4', 'sun_type4'),
    ('Sun Type 5', 'sun_type5'),
    ('Sun Type 6 (USB)', 'sun_type6'),
    ('Sun Type 6 (Tuv)', 'sun_type6_tuv'),
    ('Sun Type 7 (USB)', 'sun_type7'),
    ('Targa Visionary 811', 'targa_v811'),
    ('Toshiba Satellite S3000', 'toshsat_s300'),
    ('TypeMatrix EZ-Reach 2020', 'tm2020'),
    ('TypeMatrix EZ-Reach 2030PS', 'tm2030ps'),
    ('TypeMatrix EZ-Reach 2030PS (Intl)', 'tm2030usb'),
    ('Unitek KB-1925', 'unitekkb1925'),
    ('Yahoo! Internet keyboard', 'yahoo'),
]

ACCEL_PROFILE_OPTIONS = [
    ('Adaptive', 'adaptive'),
    ('Flat', 'flat'),
    ('Libinput', '[[Empty]]'),
]

EMULATE_DISCRETE_SCROLL_OPTIONS = [
    ('Disabled', '0'),
    ('Enabled', '1'),
    ('When no hi-res', '2'),
]

SCROLL_METHOD_OPTIONS = [
    ('2 Fingers', '2fg'),
    ('Edge', 'edge'),
    ('Scroll Wheel Pressed', 'on_button_down'),
    ('Disabled', 'no_scroll'),
]

FOLLOW_MOUSE_OPTIONS = [
    ('Full / Always (default)', '1'),
    ('Disabled', '0'),
    ('Full / Mouse Moved', '2'),
    ('Full / Always (loose focus)', '3'),
]

OFF_WINDOW_AXIS_OPTIONS = [
    ('Freeze active (default)', '0'),
    ('Send to Focused', '1'),
    ('Send to Mouse', '2'),
    ('Inactive Pass-thru', '3'),
]

FOCUS_ON_CLOSE_OPTIONS = [
    ('History (default)', '0'),
    ('Next Window', '1'),
]

FLOAT_SWITCH_OVERRIDE_OPTIONS = [
    ('Disabled', '0'),
    ('Enabled (default)', '1'),
    ('Reset Focus (on click)', '2'),
]

DRAG_LOCK_OPTIONS = [
    ('Disabled (default)', '0'),
    ('Enabled', '1'),
    ('Enabled (until timeout)', '2'),
]

DRAG_3FG_OPTIONS = [
    ('Disabled (default)', '0'),
    ('Enabled (fullscreen)', '1'),
    ('Enabled (tiled)', '2'),
    ('Enabled (all)', '3'),
]

TAP_BUTTON_MAP_OPTIONS = [
    ('Left, Right, Middle (default)', 'lrm'),
    ('Left, Middle, Right', 'lmr'),
]

SHARE_STATES_OPTIONS = [
    ('Yes (default)', '1'),
    ('No', 0),
    ('Yes unless IME client', 2),
]

TRANSFORM_OPTIONS = [
    ('Unset', -1),
    ('Normal (no transforms)', 0),
    ('90 degrees', 1),
    ('180 degrees', 2),
    ('270 degrees', 3),
    ('Flipped', 4),
    ('Flipped + 90 degrees', 5),
    ('Flipped + 180 degrees', 6),
    ('Flipped + 270 degrees', 7),
]



# DEFAULT SETTINGS


DEFAULT_SETTINGS = {
    'kb_layout': 'us',
    'kb_variant': '',
    'kb_model': '',
    'kb_file': '',
    'resolve_binds_by_sym': False,
    'repeat_rate': 25,
    'repeat_delay': 600,
    'kb_options_shader': True,
    'mouse_sensitivity': 0.25,
    'accel_profile': 'adaptive',
    'emulate_discrete_scroll': '2',
    'force_no_accel': False,
    'rotation': 0,
    'left_handed': False,
    'scroll_method': 'on_button_down',
    'scroll_button_lock': False,
    'follow_mouse': '1',
    'follow_mouse_threshold': 0.0,
    'mouse_refocus': True,
    'special_fallthrough': False,
    'off_window_axis_events': '1',
    'focus_on_close': '0',
    'float_switch_override_focus': '1',
    'disable_while_typing': True,
    'natural_scroll': False,
    'middle_button_emulation': False,
    'clickfinger_behavior': False,
    'tap_to_click': True,
    'drag_lock': '0',
    'tap_and_drag': True,
    'flip_x': False,
    'flip_y': False,
    'drag_3fg': '0',
    'tap_button_map': 'lrm',
    'share_states': '1',
    'release_pressed_on_close': False,
    'transform': '-1',
    'output': '',
    'scroll_factor': 1.0,
}



# SETTINGS CLASS


class Settings:
    def __init__(self):
        self.config_path = CONFIG_PATH
        self.settings = DEFAULT_SETTINGS.copy()
        self.config_loaded = False
        self._ensure_config_exists()
        self.load_config()
    
    def _ensure_config_exists(self):
        """Ensure config directory and file exist - fail-safe initialization"""
        try:
            # Create parent directories if they don't exist
            self.config_path.parent.mkdir(parents=True, exist_ok=True)
            
            # If config file doesn't exist, create it with defaults
            if not self.config_path.exists():
                print(f"Config not found: {self.config_path}")
                print("Creating config directory and file with default settings...")
                self._write_default_config()
                print(f"Created: {self.config_path}")
        except PermissionError as e:
            print(f"Permission denied creating config: {e}")
            print("Will use default settings in memory.")
        except Exception as e:
            print(f"Error ensuring config exists: {e}")
            print("Will use default settings in memory.")
    
    def _write_default_config(self):
        """Write default configuration to file"""
        try:
            config_content = self.generate_config()
            self.config_path.write_text(config_content)
            return True
        except Exception as e:
            print(f"Error writing default config: {e}")
            return False
    
    def load_config(self):
        """Load configuration from file with fail-safe handling"""
        if not self.config_path.exists():
            print(f"Config file not found, using defaults: {self.config_path}")
            self.config_loaded = True  # Mark as loaded since we have defaults
            return
        
        try:
            content = self.config_path.read_text()
            self._parse_config(content)
            self.config_loaded = True
            print(f"Config loaded successfully: {self.config_path}")
        except PermissionError as e:
            print(f"Permission denied reading config: {e}")
            print("Using default settings.")
            self.config_loaded = True  # Use defaults
        except Exception as e:
            print(f"Error loading config: {e}")
            print("Using default settings.")
            self.config_loaded = True  # Use defaults
    
    def _parse_config(self, content):
        for line in content.split('\n'):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if line.startswith("kb_layout ="):
                value = line.replace("kb_layout =", "").strip()
                self.settings["kb_layout"] = value
            if line.startswith("kb_variant ="):
                value = line.replace("kb_variant =", "").strip()
                self.settings["kb_variant"] = value
            if line.startswith("kb_model ="):
                value = line.replace("kb_model =", "").strip()
                self.settings["kb_model"] = value
            if line.startswith("kb_file ="):
                value = line.replace("kb_file =", "").strip()
                self.settings["kb_file"] = value
            if line.startswith("resolve_binds_by_sym ="):
                value = line.replace("resolve_binds_by_sym =", "").strip()
                self.settings["resolve_binds_by_sym"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("repeat_rate ="):
                value = line.replace("repeat_rate =", "").strip()
                try:
                    self.settings["repeat_rate"] = int(float(value))
                except: pass
            if line.startswith("repeat_delay ="):
                value = line.replace("repeat_delay =", "").strip()
                try:
                    self.settings["repeat_delay"] = int(float(value))
                except: pass
            if line.startswith("sensitivity ="):
                value = line.replace("sensitivity =", "").strip()
                try:
                    self.settings["mouse_sensitivity"] = float(value)
                except: pass
            if line.startswith("accel_profile ="):
                value = line.replace("accel_profile =", "").strip()
                self.settings["accel_profile"] = value
            if line.startswith("emulate_discrete_scroll ="):
                value = line.replace("emulate_discrete_scroll =", "").strip()
                self.settings["emulate_discrete_scroll"] = value
            if line.startswith("force_no_accel ="):
                value = line.replace("force_no_accel =", "").strip()
                self.settings["force_no_accel"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("rotation ="):
                value = line.replace("rotation =", "").strip()
                try:
                    self.settings["rotation"] = int(float(value))
                except: pass
            if line.startswith("left_handed ="):
                value = line.replace("left_handed =", "").strip()
                self.settings["left_handed"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("scroll_method ="):
                value = line.replace("scroll_method =", "").strip()
                self.settings["scroll_method"] = value
            if line.startswith("natural_scroll ="):
                value = line.replace("natural_scroll =", "").strip()
                self.settings["natural_scroll"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("follow_mouse ="):
                value = line.replace("follow_mouse =", "").strip()
                self.settings["follow_mouse"] = value
            if line.startswith("follow_mouse_threshold ="):
                value = line.replace("follow_mouse_threshold =", "").strip()
                try:
                    self.settings["follow_mouse_threshold"] = float(value)
                except: pass
            if line.startswith("mouse_refocus ="):
                value = line.replace("mouse_refocus =", "").strip()
                self.settings["mouse_refocus"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("special_fallthrough ="):
                value = line.replace("special_fallthrough =", "").strip()
                self.settings["special_fallthrough"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("off_window_axis_events ="):
                value = line.replace("off_window_axis_events =", "").strip()
                self.settings["off_window_axis_events"] = value
            if line.startswith("focus_on_close ="):
                value = line.replace("focus_on_close =", "").strip()
                self.settings["focus_on_close"] = value
            if line.startswith("disable_while_typing ="):
                value = line.replace("disable_while_typing =", "").strip()
                self.settings["disable_while_typing"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("natural_scroll ="):
                value = line.replace("natural_scroll =", "").strip()
                self.settings["natural_scroll"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("scroll_factor ="):
                value = line.replace("scroll_factor =", "").strip()
                try:
                    self.settings["scroll_factor"] = float(value)
                except: pass
            if line.startswith("middle_button_emulation ="):
                value = line.replace("middle_button_emulation =", "").strip()
                self.settings["middle_button_emulation"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("clickfinger_behavior ="):
                value = line.replace("clickfinger_behavior =", "").strip()
                self.settings["clickfinger_behavior"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("tap-to-click ="):
                value = line.replace("tap-to-click =", "").strip()
                self.settings["tap_to_click"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("drag_lock ="):
                value = line.replace("drag_lock =", "").strip()
                self.settings["drag_lock"] = value
            if line.startswith("tap-and-drag ="):
                value = line.replace("tap-and-drag =", "").strip()
                self.settings["tap_and_drag"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("flip_x ="):
                value = line.replace("flip_x =", "").strip()
                self.settings["flip_x"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("flip_y ="):
                value = line.replace("flip_y =", "").strip()
                self.settings["flip_y"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("drag_3fg ="):
                value = line.replace("drag_3fg =", "").strip()
                self.settings["drag_3fg"] = value
            if line.startswith("tap_button_map ="):
                value = line.replace("tap_button_map =", "").strip()
                self.settings["tap_button_map"] = value
            if line.startswith("share_states ="):
                value = line.replace("share_states =", "").strip()
                self.settings["share_states"] = value
            if line.startswith("release_pressed_on_close ="):
                value = line.replace("release_pressed_on_close =", "").strip()
                self.settings["release_pressed_on_close"] = value.lower() in ("true", "1", "yes", "on")
            if line.startswith("transform ="):
                value = line.replace("transform =", "").strip()
                self.settings["transform"] = value
            if line.startswith("output ="):
                value = line.replace("output =", "").strip()
                self.settings["output"] = value

    def generate_config(self):
        s = self.settings
        lines = []
        lines.append("##=============================================##")
        lines.append(" #        Yggdrasil's -  Input Settings        #")
        lines.append(" #          Hyprland - Configuration           #")
        lines.append("##=============================================##")
        lines.append("# Generated by Yggdrasil Input Settings GUI    #")
        lines.append("##=============================================##")
        lines.append(" ")
        lines.append("input {")
        lines.append("    kb_layout = " + str(s["kb_layout"]))
        lines.append("    kb_variant = " + str(s["kb_variant"]))
        lines.append("    kb_model = " + str(s["kb_model"]))
        lines.append("    kb_file = " + str(s["kb_file"]))
        lines.append("    resolve_binds_by_sym = " + ("true" if s["resolve_binds_by_sym"] else "false"))
        lines.append("    repeat_rate = " + str(int(s["repeat_rate"])))
        lines.append("    repeat_delay = " + str(int(s["repeat_delay"])))
        if s["kb_options_shader"]:
            lines.append("    kb_options = caps:hyper")
        lines.append("    sensitivity = " + f'{s["mouse_sensitivity"]:.4f}')
        lines.append("    scroll_factor = " + f'{s["scroll_factor"]:.2f}')
        lines.append("    accel_profile = " + str(s["accel_profile"]))
        lines.append("    emulate_discrete_scroll = " + str(s["emulate_discrete_scroll"]))
        lines.append("    force_no_accel = " + ("true" if s["force_no_accel"] else "false"))
        lines.append("    rotation = " + str(int(s["rotation"])))
        lines.append("    left_handed = " + ("true" if s["left_handed"] else "false"))
        lines.append("    scroll_method = " + str(s["scroll_method"]))
        lines.append("    scroll_button_lock = " + ("true" if s["scroll_button_lock"] else "false"))
        lines.append("    natural_scroll = " + ("true" if s["natural_scroll"] else "false"))
        lines.append("    follow_mouse = " + str(s["follow_mouse"]))
        lines.append("    follow_mouse_threshold = " + f'{s["follow_mouse_threshold"]:.2f}')
        lines.append("    mouse_refocus = " + ("true" if s["mouse_refocus"] else "false"))
        lines.append("    special_fallthrough = " + ("true" if s["special_fallthrough"] else "false"))
        lines.append("    off_window_axis_events = " + str(s["off_window_axis_events"]))
        lines.append("    focus_on_close = " + str(s["focus_on_close"]))
        lines.append("    float_switch_override_focus = " + str(s["float_switch_override_focus"]))
        lines.append("")
        lines.append("    touchpad {")
        lines.append("        disable_while_typing = " + ("true" if s["disable_while_typing"] else "false"))
        lines.append("        natural_scroll = " + ("true" if s["natural_scroll"] else "false"))
        lines.append("        scroll_factor = " + f'{s["scroll_factor"]:.2f}')
        lines.append("        middle_button_emulation = " + ("true" if s["middle_button_emulation"] else "false"))
        lines.append("        clickfinger_behavior = " + ("true" if s["clickfinger_behavior"] else "false"))
        lines.append("        tap-to-click = " + ("true" if s["tap_to_click"] else "false"))
        lines.append("        drag_lock = " + str(s["drag_lock"]))
        lines.append("        tap-and-drag = " + ("true" if s["tap_and_drag"] else "false"))
        lines.append("        flip_x = " + ("true" if s["flip_x"] else "false"))
        lines.append("        flip_y = " + ("true" if s["flip_y"] else "false"))
        lines.append("        drag_3fg = " + str(s["drag_3fg"]))
        lines.append("        tap_button_map = " + str(s["tap_button_map"]))
        lines.append("    }")
        lines.append("")
        lines.append("    virtualkeyboard {")
        lines.append("        share_states = " + str(s["share_states"]))
        lines.append("        release_pressed_on_close = " + ("true" if s["release_pressed_on_close"] else "false"))
        lines.append("    }")
        lines.append("")
        lines.append("    touchdevice {")
        lines.append("        transform = " + str(s["transform"]))
        lines.append("        output = " + str(s["output"]))
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines)
    
    def save_config(self):
        """Save configuration to file with fail-safe handling"""
        try:
            # Ensure directory exists
            self.config_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Create backup if config exists
            if self.config_path.exists():
                import shutil
                backup_path = self.config_path.with_suffix(".conf.backup")
                try:
                    shutil.copy2(self.config_path, backup_path)
                except Exception as e:
                    print(f"Warning: Could not create backup: {e}")
            
            # Write new config
            self.config_path.write_text(self.generate_config())
            return True
        except PermissionError as e:
            print(f"Permission denied saving config: {e}")
            return False
        except Exception as e:
            print(f"Error saving config: {e}")
            return False
    
    def reset_to_defaults(self):
        self.settings = DEFAULT_SETTINGS.copy()



# WIDGET CLASSES


class DropdownRow(Adw.ActionRow):
    def __init__(self, title, subtitle, options, current_value, callback):
        super().__init__()
        self.set_title(title)
        if subtitle:
            self.set_subtitle(subtitle)
        self.options = options
        self.callback = callback
        
        string_list = Gtk.StringList()
        current_index = 0
        for i, (label, value) in enumerate(options):
            string_list.append(label)
            if value == current_value:
                current_index = i
        
        self.dropdown = Gtk.DropDown(model=string_list)
        self.dropdown.set_selected(current_index)
        self.dropdown.set_valign(Gtk.Align.CENTER)
        self.dropdown.connect("notify::selected", self._on_selected)
        self.add_suffix(self.dropdown)
    
    def _on_selected(self, dropdown, _):
        idx = dropdown.get_selected()
        if idx < len(self.options):
            _, value = self.options[idx]
            self.callback(value)
    
    def set_value(self, value):
        for i, (_, v) in enumerate(self.options):
            if v == value:
                self.dropdown.set_selected(i)
                break


class SwitchRow(Adw.ActionRow):
    def __init__(self, title, subtitle, active, callback):
        super().__init__()
        self.set_title(title)
        if subtitle:
            self.set_subtitle(subtitle)
        self.callback = callback
        
        self.switch = Gtk.Switch(valign=Gtk.Align.CENTER)
        self.switch.set_active(active)
        self.switch.connect("notify::active", self._on_toggled)
        self.add_suffix(self.switch)
        self.set_activatable_widget(self.switch)
    
    def _on_toggled(self, switch, _):
        self.callback(switch.get_active())
    
    def set_active(self, active):
        self.switch.set_active(active)


class SliderRow(Adw.ActionRow):
    def __init__(self, title, subtitle, min_val, max_val, step, value, callback, digits=2):
        super().__init__()
        self.set_title(title)
        if subtitle:
            self.set_subtitle(subtitle)
        self.callback = callback
        
        self.adjustment = Gtk.Adjustment(
            value=value, lower=min_val, upper=max_val,
            step_increment=step, page_increment=step * 10
        )
        self.scale = Gtk.Scale(
            orientation=Gtk.Orientation.HORIZONTAL,
            adjustment=self.adjustment,
            draw_value=True, digits=digits
        )
        self.scale.set_size_request(200, -1)
        self.scale.connect("value-changed", self._on_changed)
        self.add_suffix(self.scale)
    
    def _on_changed(self, scale):
        self.callback(scale.get_value())
    
    def set_value(self, value):
        self.adjustment.set_value(value)


class EntryRow(Adw.ActionRow):
    def __init__(self, title, subtitle, value, callback, placeholder=""):
        super().__init__()
        self.set_title(title)
        if subtitle:
            self.set_subtitle(subtitle)
        self.callback = callback
        
        self.entry = Gtk.Entry()
        self.entry.set_text(str(value))
        self.entry.set_placeholder_text(placeholder)
        self.entry.set_valign(Gtk.Align.CENTER)
        self.entry.set_size_request(200, -1)
        self.entry.connect("changed", self._on_changed)
        self.add_suffix(self.entry)
    
    def _on_changed(self, entry):
        self.callback(entry.get_text())
    
    def set_text(self, text):
        self.entry.set_text(str(text))


class InfoRow(Adw.ActionRow):
    """Display-only text row for information"""
    def __init__(self, title, subtitle=""):
        super().__init__()
        if title:
            self.set_title(title)
        if subtitle:
            self.set_subtitle(subtitle)
        self.set_activatable(False)


class InfoBox(Adw.ActionRow):
    """Multi-line information box"""
    def __init__(self, title, text):
        super().__init__()
        if title:
            self.set_title(title)
        if text:
            self.set_subtitle(text)
        self.set_activatable(False)
        self.set_subtitle_lines(10)  # Allow more lines


class ButtonRow(Adw.ActionRow):
    """Button that runs a command"""
    def __init__(self, title, subtitle, button_label, command, use_pkexec=False, callback=None):
        super().__init__()
        self.set_title(title)
        if subtitle:
            self.set_subtitle(subtitle)
        self.command = command
        self.use_pkexec = use_pkexec
        self.callback = callback
        
        button = Gtk.Button(label=button_label)
        button.set_valign(Gtk.Align.CENTER)
        button.connect("clicked", self._on_clicked)
        self.add_suffix(button)
    
    def _on_clicked(self, button):
        try:
            if self.use_pkexec:
                cmd = ["pkexec", "bash", "-c", self.command]
            else:
                cmd = ["bash", "-c", self.command]
            
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if self.callback:
                if result.returncode == 0:
                    self.callback(True, "Command executed successfully")
                else:
                    self.callback(False, result.stderr or "Command failed")
        except Exception as e:
            if self.callback:
                self.callback(False, str(e))


class ButtonBox(Gtk.Box):
    """Row of multiple buttons"""
    def __init__(self, buttons, callback=None):
        super().__init__(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        self.set_margin_top(8)
        self.set_margin_bottom(8)
        self.set_margin_start(12)
        self.set_margin_end(12)
        self.set_halign(Gtk.Align.CENTER)
        self.callback = callback
        
        for btn_data in buttons:
            button = Gtk.Button(label=btn_data['label'])
            button.connect("clicked", self._on_clicked, btn_data)
            if btn_data.get('suggested'):
                button.add_css_class("suggested-action")
            if btn_data.get('destructive'):
                button.add_css_class("destructive-action")
            self.append(button)
    
    def _on_clicked(self, button, btn_data):
        cmd = btn_data.get('command', '')
        use_pkexec = btn_data.get('pkexec', False)
        
        try:
            if use_pkexec:
                full_cmd = ["pkexec", "bash", "-c", cmd]
            else:
                full_cmd = ["bash", "-c", cmd]
            
            result = subprocess.run(full_cmd, capture_output=True, text=True)
            
            if self.callback:
                if result.returncode == 0:
                    self.callback(True, f"{btn_data['label']}: Success")
                else:
                    self.callback(False, result.stderr or f"{btn_data['label']}: Failed")
        except Exception as e:
            if self.callback:
                self.callback(False, str(e))



# MAIN WINDOW


class MainWindow(Adw.ApplicationWindow):
    def __init__(self, app):
        super().__init__(application=app)
        self.set_title(APP_TITLE)
        self.set_default_size(WINDOW_WIDTH, WINDOW_HEIGHT)
        
        # Initialize settings with fail-safe handling
        try:
            self.settings = Settings()
        except Exception as e:
            print(f"Critical error initializing settings: {e}")
            print("Starting with default settings...")
            self.settings = Settings.__new__(Settings)
            self.settings.config_path = CONFIG_PATH
            self.settings.settings = DEFAULT_SETTINGS.copy()
            self.settings.config_loaded = True
        
        self.widgets = {}
        self.checklist_checkbuttons = {}
        
        self.status_bar = Gtk.Label(label="Ready")
        self.status_bar.set_margin_top(4)
        self.status_bar.set_margin_bottom(4)
        
        self._build_ui()
    
    def _build_ui(self):
        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        
        # Header bar with buttons
        header = Adw.HeaderBar()
        
        apply_btn = Gtk.Button(label="Apply")
        apply_btn.add_css_class("suggested-action")
        apply_btn.connect("clicked", self.on_apply)
        header.pack_end(apply_btn)
        
        reset_btn = Gtk.Button(label="Reset")
        reset_btn.add_css_class("destructive-action")
        reset_btn.connect("clicked", self.on_reset)
        header.pack_start(reset_btn)
        
        main_box.append(header)
        
        scrolled = Gtk.ScrolledWindow()
        scrolled.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        scrolled.set_vexpand(True)
        
        content = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        content.set_margin_top(12)
        content.set_margin_bottom(12)
        content.set_margin_start(12)
        content.set_margin_end(12)

        # === Keyboard ===
        keyboard_group = Adw.PreferencesGroup(
            title="Keyboard",
            description="Keyboard layout, variant, and behavior settings"
        )

        # Keyboard Layout
        row_kb_layout = Adw.ActionRow()
        row_kb_layout.set_title("Keyboard Layout")
        row_kb_layout.set_subtitle("Appropriate XKB keyboard layout, for example 'us' or 'de'.")
        string_list_kb_layout = Gtk.StringList()
        current_idx_kb_layout = 0
        for i, (label, value) in enumerate(KB_LAYOUT_OPTIONS):
            string_list_kb_layout.append(label)
            if value == self.settings.settings['kb_layout']:
                current_idx_kb_layout = i
        dropdown_kb_layout = Gtk.DropDown(model=string_list_kb_layout)
        dropdown_kb_layout.set_selected(current_idx_kb_layout)
        dropdown_kb_layout.set_valign(Gtk.Align.CENTER)
        dropdown_kb_layout.connect("notify::selected", lambda d, _, o=KB_LAYOUT_OPTIONS, k='kb_layout': self._update(k, o[d.get_selected()][1]))
        row_kb_layout.add_suffix(dropdown_kb_layout)
        self.widgets['kb_layout'] = row_kb_layout
        self.widgets['kb_layout']._dropdown = dropdown_kb_layout
        self.widgets['kb_layout']._options = KB_LAYOUT_OPTIONS
        keyboard_group.add(row_kb_layout)

        # Keyboard Variant
        row_kb_variant = Adw.ActionRow()
        row_kb_variant.set_title("Keyboard Variant")
        row_kb_variant.set_subtitle("Appropriate XKB keyboard variant, for example 'dvorak'.")
        string_list_kb_variant = Gtk.StringList()
        current_idx_kb_variant = 0
        for i, (label, value) in enumerate(KB_VARIANT_OPTIONS):
            string_list_kb_variant.append(label)
            if value == self.settings.settings['kb_variant']:
                current_idx_kb_variant = i
        dropdown_kb_variant = Gtk.DropDown(model=string_list_kb_variant)
        dropdown_kb_variant.set_selected(current_idx_kb_variant)
        dropdown_kb_variant.set_valign(Gtk.Align.CENTER)
        dropdown_kb_variant.connect("notify::selected", lambda d, _, o=KB_VARIANT_OPTIONS, k='kb_variant': self._update(k, o[d.get_selected()][1]))
        row_kb_variant.add_suffix(dropdown_kb_variant)
        self.widgets['kb_variant'] = row_kb_variant
        self.widgets['kb_variant']._dropdown = dropdown_kb_variant
        self.widgets['kb_variant']._options = KB_VARIANT_OPTIONS
        keyboard_group.add(row_kb_variant)

        # Keyboard Model
        row_kb_model = Adw.ActionRow()
        row_kb_model.set_title("Keyboard Model")
        row_kb_model.set_subtitle("Appropriate XKB keyboard model, such as 'pc105'. Leave blank for auto-detect.")
        string_list_kb_model = Gtk.StringList()
        current_idx_kb_model = 0
        for i, (label, value) in enumerate(KB_MODEL_OPTIONS):
            string_list_kb_model.append(label)
            if value == self.settings.settings['kb_model']:
                current_idx_kb_model = i
        dropdown_kb_model = Gtk.DropDown(model=string_list_kb_model)
        dropdown_kb_model.set_selected(current_idx_kb_model)
        dropdown_kb_model.set_valign(Gtk.Align.CENTER)
        dropdown_kb_model.connect("notify::selected", lambda d, _, o=KB_MODEL_OPTIONS, k='kb_model': self._update(k, o[d.get_selected()][1]))
        row_kb_model.add_suffix(dropdown_kb_model)
        self.widgets['kb_model'] = row_kb_model
        self.widgets['kb_model']._dropdown = dropdown_kb_model
        self.widgets['kb_model']._options = KB_MODEL_OPTIONS
        keyboard_group.add(row_kb_model)

        # Keyboard File Path
        row_kb_file = Adw.ActionRow()
        row_kb_file.set_title("Keyboard File Path")
        row_kb_file.set_subtitle("If set, the path to a custom XKB keymap file. Usually leave blank.")
        entry_kb_file = Gtk.Entry()
        entry_kb_file.set_text(str(self.settings.settings['kb_file']))
        entry_kb_file.set_valign(Gtk.Align.CENTER)
        entry_kb_file.set_size_request(200, -1)
        entry_kb_file.connect("changed", lambda e, k='kb_file': self._update(k, e.get_text()))
        row_kb_file.add_suffix(entry_kb_file)
        self.widgets['kb_file'] = row_kb_file
        self.widgets['kb_file']._entry = entry_kb_file
        keyboard_group.add(row_kb_file)

        # Resolve Key Binds by Symbol
        row_resolve_binds_by_sym = Adw.ActionRow()
        row_resolve_binds_by_sym.set_title(" Resolve Key Binds by Symbol")
        row_resolve_binds_by_sym.set_subtitle("Determines how keybinds act when multiple layouts are used. If false, keybinds will always act as if the first specified layout is active. If true, keybinds specified by symbols are activated when you type the respective symbol with the current layout.")
        switch_resolve_binds_by_sym = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_resolve_binds_by_sym.set_active(self.settings.settings['resolve_binds_by_sym'])
        switch_resolve_binds_by_sym.connect("notify::active", lambda s, _, k='resolve_binds_by_sym': self._update(k, s.get_active()))
        row_resolve_binds_by_sym.add_suffix(switch_resolve_binds_by_sym)
        row_resolve_binds_by_sym.set_activatable_widget(switch_resolve_binds_by_sym)
        self.widgets['resolve_binds_by_sym'] = row_resolve_binds_by_sym
        self.widgets['resolve_binds_by_sym']._switch = switch_resolve_binds_by_sym
        keyboard_group.add(row_resolve_binds_by_sym)

        # Key's Repeat Rate
        row_repeat_rate = Adw.ActionRow()
        row_repeat_rate.set_title("Key's Repeat Rate")
        row_repeat_rate.set_subtitle("The repeat rate for held-down keys, in repeats per second. (default is 25)")
        adj_repeat_rate = Gtk.Adjustment(value=self.settings.settings['repeat_rate'], lower=0.0, upper=100.0, step_increment=1.0, page_increment=10.0)
        scale_repeat_rate = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adj_repeat_rate, draw_value=True, digits=0, hexpand=True)
        scale_repeat_rate.set_size_request(200, -1)
        scale_repeat_rate.connect("value-changed", lambda s, k='repeat_rate': self._update(k, int(s.get_value())))
        row_repeat_rate.add_suffix(scale_repeat_rate)
        self.widgets['repeat_rate'] = row_repeat_rate
        self.widgets['repeat_rate']._scale = scale_repeat_rate
        keyboard_group.add(row_repeat_rate)

        # Key's delay
        row_repeat_delay = Adw.ActionRow()
        row_repeat_delay.set_title("Key's Delay")
        row_repeat_delay.set_subtitle("Delay before a held-down key is repeated, in milliseconds. (default is 600)")
        adj_repeat_delay = Gtk.Adjustment(value=self.settings.settings['repeat_delay'],  lower=0, upper=1200, step_increment=25, page_increment=250)
        scale_repeat_delay = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adj_repeat_delay, draw_value=True, digits=0, hexpand=True)
        scale_repeat_delay.set_size_request(200, -1)
        scale_repeat_delay.connect("value-changed", lambda s, k='repeat_delay': self._update(k, int(s.get_value())))
        row_repeat_delay.add_suffix(scale_repeat_delay)
        self.widgets['repeat_delay'] = row_repeat_delay
        self.widgets['repeat_delay']._scale = scale_repeat_delay
        keyboard_group.add(row_repeat_delay)

        # CAPS as Nordix Shader Bottom
        row_kb_options_shader = Adw.ActionRow()
        row_kb_options_shader.set_title("CAPS as Nordix Shader Bottom")
        row_kb_options_shader.set_subtitle("Disable CPAS default functions and replace it with Nordix shader toggle system")
        switch_kb_options_shader = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_kb_options_shader.set_active(self.settings.settings['kb_options_shader'])
        switch_kb_options_shader.connect("notify::active", lambda s, _, k='kb_options_shader': self._update(k, s.get_active()))
        row_kb_options_shader.add_suffix(switch_kb_options_shader)
        row_kb_options_shader.set_activatable_widget(switch_kb_options_shader)
        self.widgets['kb_options_shader'] = row_kb_options_shader
        self.widgets['kb_options_shader']._switch = switch_kb_options_shader
        keyboard_group.add(row_kb_options_shader)


        content.append(keyboard_group)

        # === Mouse ===
        mouse_group = Adw.PreferencesGroup(
            title="Mouse",
            description="Mouse sensitivity, acceleration and button settings"
        )

        # Sensitivity
        row_mouse_sensitivity = Adw.ActionRow()
        row_mouse_sensitivity.set_title("Sensitivity")
        row_mouse_sensitivity.set_subtitle("Sets the mouse input sensitivity.")
        adj_mouse_sensitivity = Gtk.Adjustment(value=self.settings.settings['mouse_sensitivity'], lower=0.0, upper=1.0, step_increment=0.005, page_increment=0.05)
        scale_mouse_sensitivity = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adj_mouse_sensitivity, draw_value=True, digits=4, hexpand=True)
        scale_mouse_sensitivity.set_size_request(200, -1)
        scale_mouse_sensitivity.connect("value-changed", lambda s, k='mouse_sensitivity': self._update(k, s.get_value()))
        row_mouse_sensitivity.add_suffix(scale_mouse_sensitivity)
        self.widgets['mouse_sensitivity'] = row_mouse_sensitivity
        self.widgets['mouse_sensitivity']._scale = scale_mouse_sensitivity
        mouse_group.add(row_mouse_sensitivity)

        # Adaptive Mouse Acceleration
        row_accel_profile = Adw.ActionRow()
        row_accel_profile.set_title("Adaptive Mouse Acceleration")
        row_accel_profile.set_subtitle("Sets the cursor acceleration profile. Can be one of adaptive, flat or libinput. Can also be custom (Not suported in Nordix Setting GUI)")
        string_list_accel_profile = Gtk.StringList()
        current_idx_accel_profile = 0
        for i, (label, value) in enumerate(ACCEL_PROFILE_OPTIONS):
            string_list_accel_profile.append(label)
            if value == self.settings.settings['accel_profile']:
                current_idx_accel_profile = i
        dropdown_accel_profile = Gtk.DropDown(model=string_list_accel_profile)
        dropdown_accel_profile.set_selected(current_idx_accel_profile)
        dropdown_accel_profile.set_valign(Gtk.Align.CENTER)
        dropdown_accel_profile.connect("notify::selected", lambda d, _, o=ACCEL_PROFILE_OPTIONS, k='accel_profile': self._update(k, o[d.get_selected()][1]))
        row_accel_profile.add_suffix(dropdown_accel_profile)
        self.widgets['accel_profile'] = row_accel_profile
        self.widgets['accel_profile']._dropdown = dropdown_accel_profile
        self.widgets['accel_profile']._options = ACCEL_PROFILE_OPTIONS
        mouse_group.add(row_accel_profile)

        # Force no Cursor Acceleration
        row_force_no_accel = Adw.ActionRow()
        row_force_no_accel.set_title("Force no Cursor Acceleration")
        row_force_no_accel.set_subtitle("This bypasses most of your pointer settings to get as raw of a signal as possible. Enabling this is not recommended due to potential cursor desynchronization.")
        switch_force_no_accel = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_force_no_accel.set_active(self.settings.settings['force_no_accel'])
        switch_force_no_accel.connect("notify::active", lambda s, _, k='force_no_accel': self._update(k, s.get_active()))
        row_force_no_accel.add_suffix(switch_force_no_accel)
        row_force_no_accel.set_activatable_widget(switch_force_no_accel)
        self.widgets['force_no_accel'] = row_force_no_accel
        self.widgets['force_no_accel']._switch = switch_force_no_accel
        mouse_group.add(row_force_no_accel)

        # Mouse Rotation
        row_rotation = Adw.ActionRow()
        row_rotation.set_title("Mouse Rotation")
        row_rotation.set_subtitle("Sets the rotation of a device in degrees clockwise off the logical neutral position. Value is clamped to the range 0 to 359.")
        adj_rotation = Gtk.Adjustment(value=self.settings.settings['rotation'], lower=0.0, upper=359.0, step_increment=1.0, page_increment=10.0)
        scale_rotation = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adj_rotation, draw_value=True, digits=0, hexpand=True)
        scale_rotation.set_size_request(200, -1)
        scale_rotation.connect("value-changed", lambda s, k='rotation': self._update(k, int(s.get_value())))
        row_rotation.add_suffix(scale_rotation)
        self.widgets['rotation'] = row_rotation
        self.widgets['rotation']._scale = scale_rotation
        mouse_group.add(row_rotation)

        # Left Handed
        row_left_handed = Adw.ActionRow()
        row_left_handed.set_title("Left Handed")
        row_left_handed.set_subtitle("Switches the location of the right mouse button and left mouse button")
        switch_left_handed = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_left_handed.set_active(self.settings.settings['left_handed'])
        switch_left_handed.connect("notify::active", lambda s, _, k='left_handed': self._update(k, s.get_active()))
        row_left_handed.add_suffix(switch_left_handed)
        row_left_handed.set_activatable_widget(switch_left_handed)
        self.widgets['left_handed'] = row_left_handed
        self.widgets['left_handed']._switch = switch_left_handed
        mouse_group.add(row_left_handed)

        content.append(mouse_group)

        # === Scroll ===
        scroll_group = Adw.PreferencesGroup(
            title="Scroll",
            description="Scroll speed, method and direction settings"
        )

        # Scroll Speed
        row_scroll_factor = Adw.ActionRow()
        row_scroll_factor.set_title("Scroll Speed")
        row_scroll_factor.set_subtitle("Multiplier added to scroll movement for external mice. (Default = 1.0)")
        adj_scroll_factor = Gtk.Adjustment(value=self.settings.settings['scroll_factor'], lower=0.0, upper=5.0, step_increment=0.05, page_increment=0.5)
        scale_scroll_factor = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adj_scroll_factor, draw_value=True, digits=2, hexpand=True)
        scale_scroll_factor.set_size_request(200, -1)
        scale_scroll_factor.connect("value-changed", lambda s, k='scroll_factor': self._update(k, s.get_value()))
        row_scroll_factor.add_suffix(scale_scroll_factor)
        self.widgets['scroll_factor'] = row_scroll_factor
        self.widgets['scroll_factor']._scale = scale_scroll_factor
        scroll_group.add(row_scroll_factor)

        # Emulate Discrete Scroll
        row_emulate_discrete_scroll = Adw.ActionRow()
        row_emulate_discrete_scroll.set_title("Emulate Discrete Scroll")
        row_emulate_discrete_scroll.set_subtitle("Emulates discrete scrolling from high resolution scrolling events.")
        string_list_emulate_discrete_scroll = Gtk.StringList()
        current_idx_emulate_discrete_scroll = 0
        for i, (label, value) in enumerate(EMULATE_DISCRETE_SCROLL_OPTIONS):
            string_list_emulate_discrete_scroll.append(label)
            if value == self.settings.settings['emulate_discrete_scroll']:
                current_idx_emulate_discrete_scroll = i
        dropdown_emulate_discrete_scroll = Gtk.DropDown(model=string_list_emulate_discrete_scroll)
        dropdown_emulate_discrete_scroll.set_selected(current_idx_emulate_discrete_scroll)
        dropdown_emulate_discrete_scroll.set_valign(Gtk.Align.CENTER)
        dropdown_emulate_discrete_scroll.connect("notify::selected", lambda d, _, o=EMULATE_DISCRETE_SCROLL_OPTIONS, k='emulate_discrete_scroll': self._update(k, o[d.get_selected()][1]))
        row_emulate_discrete_scroll.add_suffix(dropdown_emulate_discrete_scroll)
        self.widgets['emulate_discrete_scroll'] = row_emulate_discrete_scroll
        self.widgets['emulate_discrete_scroll']._dropdown = dropdown_emulate_discrete_scroll
        self.widgets['emulate_discrete_scroll']._options = EMULATE_DISCRETE_SCROLL_OPTIONS
        scroll_group.add(row_emulate_discrete_scroll)

        # Scroll Method
        row_scroll_method = Adw.ActionRow()
        row_scroll_method.set_title("Scroll Method")
        row_scroll_method.set_subtitle("Sets the scroll method. Can be one of 2fg (2 fingers method. Can be one of 2fg (2 fingers), Edge, Scringers), Edge, Scroll wheel pressed down, Disabled")
        string_list_scroll_method = Gtk.StringList()
        current_idx_scroll_method = 0
        for i, (label, value) in enumerate(SCROLL_METHOD_OPTIONS):
            string_list_scroll_method.append(label)
            if value == self.settings.settings['scroll_method']:
                current_idx_scroll_method = i
        dropdown_scroll_method = Gtk.DropDown(model=string_list_scroll_method)
        dropdown_scroll_method.set_selected(current_idx_scroll_method)
        dropdown_scroll_method.set_valign(Gtk.Align.CENTER)
        dropdown_scroll_method.connect("notify::selected", lambda d, _, o=SCROLL_METHOD_OPTIONS, k='scroll_method': self._update(k, o[d.get_selected()][1]))
        row_scroll_method.add_suffix(dropdown_scroll_method)
        self.widgets['scroll_method'] = row_scroll_method
        self.widgets['scroll_method']._dropdown = dropdown_scroll_method
        self.widgets['scroll_method']._options = SCROLL_METHOD_OPTIONS
        scroll_group.add(row_scroll_method)

        # Scroll Button Lock
        row_scroll_button_lock = Adw.ActionRow()
        row_scroll_button_lock.set_title("Scroll Button Lock")
        row_scroll_button_lock.set_subtitle("If the scroll button lock is enabled, the button does not need to be held down. Pressing and releasing the button toggles the button lock, which logically holds the button down or releases it. While the button is logically held down, motion events are converted to scroll events.")
        switch_scroll_button_lock = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_scroll_button_lock.set_active(self.settings.settings['scroll_button_lock'])
        switch_scroll_button_lock.connect("notify::active", lambda s, _, k='scroll_button_lock': self._update(k, s.get_active()))
        row_scroll_button_lock.add_suffix(switch_scroll_button_lock)
        row_scroll_button_lock.set_activatable_widget(switch_scroll_button_lock)
        self.widgets['scroll_button_lock'] = row_scroll_button_lock
        self.widgets['scroll_button_lock']._switch = switch_scroll_button_lock
        scroll_group.add(row_scroll_button_lock)

        # Inverts Scrolling Direction
        row_natural_scroll = Adw.ActionRow()
        row_natural_scroll.set_title("Inverts Scrolling Direction")
        row_natural_scroll.set_subtitle("When enabled, scrolling moves content directly, rather than manipulating a scrollbar.")
        switch_natural_scroll = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_natural_scroll.set_active(self.settings.settings['natural_scroll'])
        switch_natural_scroll.connect("notify::active", lambda s, _, k='natural_scroll': self._update(k, s.get_active()))
        row_natural_scroll.add_suffix(switch_natural_scroll)
        row_natural_scroll.set_activatable_widget(switch_natural_scroll)
        self.widgets['natural_scroll'] = row_natural_scroll
        self.widgets['natural_scroll']._switch = switch_natural_scroll
        scroll_group.add(row_natural_scroll)

        content.append(scroll_group)

        # === Focus ===
        focus_group = Adw.PreferencesGroup(
            title="Focus",
            description="Window focus and mouse interaction behavior"
        )

        # Follow Mouse
        row_follow_mouse = Adw.ActionRow()
        row_follow_mouse.set_title("Follow Mouse")
        row_follow_mouse.set_subtitle("Sets the mode for window focus following the mouse cursor.")
        string_list_follow_mouse = Gtk.StringList()
        current_idx_follow_mouse = 0
        for i, (label, value) in enumerate(FOLLOW_MOUSE_OPTIONS):
            string_list_follow_mouse.append(label)
            if value == self.settings.settings['follow_mouse']:
                current_idx_follow_mouse = i
        dropdown_follow_mouse = Gtk.DropDown(model=string_list_follow_mouse)
        dropdown_follow_mouse.set_selected(current_idx_follow_mouse)
        dropdown_follow_mouse.set_valign(Gtk.Align.CENTER)
        dropdown_follow_mouse.connect("notify::selected", lambda d, _, o=FOLLOW_MOUSE_OPTIONS, k='follow_mouse': self._update(k, o[d.get_selected()][1]))
        row_follow_mouse.add_suffix(dropdown_follow_mouse)
        self.widgets['follow_mouse'] = row_follow_mouse
        self.widgets['follow_mouse']._dropdown = dropdown_follow_mouse
        self.widgets['follow_mouse']._options = FOLLOW_MOUSE_OPTIONS
        focus_group.add(row_follow_mouse)

        # Follow Mouse Threshold
        row_follow_mouse_threshold = Adw.ActionRow()
        row_follow_mouse_threshold.set_title(" Follow Mouse Threshold")
        row_follow_mouse_threshold.set_subtitle("Distance threshold in pixels before focus changes. 0 = instant.")
        adj_follow_mouse_threshold = Gtk.Adjustment(value=self.settings.settings['follow_mouse_threshold'], lower=0.0, upper=100.0, step_increment=1.0, page_increment=10.0)
        scale_follow_mouse_threshold = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adj_follow_mouse_threshold, draw_value=True, digits=2, hexpand=True)
        scale_follow_mouse_threshold.set_size_request(200, -1)
        scale_follow_mouse_threshold.connect("value-changed", lambda s, k='follow_mouse_threshold': self._update(k, s.get_value()))
        row_follow_mouse_threshold.add_suffix(scale_follow_mouse_threshold)
        self.widgets['follow_mouse_threshold'] = row_follow_mouse_threshold
        self.widgets['follow_mouse_threshold']._scale = scale_follow_mouse_threshold
        focus_group.add(row_follow_mouse_threshold)

        # Mouse Refocus
        row_mouse_refocus = Adw.ActionRow()
        row_mouse_refocus.set_title("Mouse Refocus")
        row_mouse_refocus.set_subtitle("If disabled, mouse focus won't switch to the hovered window unless the mouse crosses a window boundary when follow_mouse is set to 1.")
        switch_mouse_refocus = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_mouse_refocus.set_active(self.settings.settings['mouse_refocus'])
        switch_mouse_refocus.connect("notify::active", lambda s, _, k='mouse_refocus': self._update(k, s.get_active()))
        row_mouse_refocus.add_suffix(switch_mouse_refocus)
        row_mouse_refocus.set_activatable_widget(switch_mouse_refocus)
        self.widgets['mouse_refocus'] = row_mouse_refocus
        self.widgets['mouse_refocus']._switch = switch_mouse_refocus
        focus_group.add(row_mouse_refocus)

        # Special Fallthrough
        row_special_fallthrough = Adw.ActionRow()
        row_special_fallthrough.set_title("Special Fallthrough")
        row_special_fallthrough.set_subtitle("If enabled, having only floating windows in the special workspace will not block focusing windows in the regular workspace.")
        switch_special_fallthrough = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_special_fallthrough.set_active(self.settings.settings['special_fallthrough'])
        switch_special_fallthrough.connect("notify::active", lambda s, _, k='special_fallthrough': self._update(k, s.get_active()))
        row_special_fallthrough.add_suffix(switch_special_fallthrough)
        row_special_fallthrough.set_activatable_widget(switch_special_fallthrough)
        self.widgets['special_fallthrough'] = row_special_fallthrough
        self.widgets['special_fallthrough']._switch = switch_special_fallthrough
        focus_group.add(row_special_fallthrough)

        # Off Window Axis Events
        row_off_window_axis_events = Adw.ActionRow()
        row_off_window_axis_events.set_title("Off Window Axis Events")
        row_off_window_axis_events.set_subtitle("Handles axis events around (gaps and borders for tiled, extract for determine window area).")
        string_list_off_window_axis_events = Gtk.StringList()
        current_idx_off_window_axis_events = 0
        for i, (label, value) in enumerate(OFF_WINDOW_AXIS_OPTIONS):
            string_list_off_window_axis_events.append(label)
            if value == self.settings.settings['off_window_axis_events']:
                current_idx_off_window_axis_events = i
        dropdown_off_window_axis_events = Gtk.DropDown(model=string_list_off_window_axis_events)
        dropdown_off_window_axis_events.set_selected(current_idx_off_window_axis_events)
        dropdown_off_window_axis_events.set_valign(Gtk.Align.CENTER)
        dropdown_off_window_axis_events.connect("notify::selected", lambda d, _, o=OFF_WINDOW_AXIS_OPTIONS, k='off_window_axis_events': self._update(k, o[d.get_selected()][1]))
        row_off_window_axis_events.add_suffix(dropdown_off_window_axis_events)
        self.widgets['off_window_axis_events'] = row_off_window_axis_events
        self.widgets['off_window_axis_events']._dropdown = dropdown_off_window_axis_events
        self.widgets['off_window_axis_events']._options = OFF_WINDOW_AXIS_OPTIONS
        focus_group.add(row_off_window_axis_events)

        # Focus on Close
        row_focus_on_close = Adw.ActionRow()
        row_focus_on_close.set_title("Focus on Close")
        row_focus_on_close.set_subtitle("Controls which window will be focused after a window is closed.")
        string_list_focus_on_close = Gtk.StringList()
        current_idx_focus_on_close = 0
        for i, (label, value) in enumerate(FOCUS_ON_CLOSE_OPTIONS):
            string_list_focus_on_close.append(label)
            if value == self.settings.settings['focus_on_close']:
                current_idx_focus_on_close = i
        dropdown_focus_on_close = Gtk.DropDown(model=string_list_focus_on_close)
        dropdown_focus_on_close.set_selected(current_idx_focus_on_close)
        dropdown_focus_on_close.set_valign(Gtk.Align.CENTER)
        dropdown_focus_on_close.connect("notify::selected", lambda d, _, o=FOCUS_ON_CLOSE_OPTIONS, k='focus_on_close': self._update(k, o[d.get_selected()][1]))
        row_focus_on_close.add_suffix(dropdown_focus_on_close)
        self.widgets['focus_on_close'] = row_focus_on_close
        self.widgets['focus_on_close']._dropdown = dropdown_focus_on_close
        self.widgets['focus_on_close']._options = FOCUS_ON_CLOSE_OPTIONS
        focus_group.add(row_focus_on_close)

        # Float Switch Override Focus
        row_float_switch_override_focus = Adw.ActionRow()
        row_float_switch_override_focus.set_title("Float Switch Override Focus")
        row_float_switch_override_focus.set_subtitle("If enabled (default), focus will change to the window under the cursor when changing from tiled-to-floating and vice versa.")
        string_list_float_switch_override_focus = Gtk.StringList()
        current_idx_float_switch_override_focus = 0
        for i, (label, value) in enumerate(FLOAT_SWITCH_OVERRIDE_OPTIONS):
            string_list_float_switch_override_focus.append(label)
            if value == self.settings.settings['float_switch_override_focus']:
                current_idx_float_switch_override_focus = i
        dropdown_float_switch_override_focus = Gtk.DropDown(model=string_list_float_switch_override_focus)
        dropdown_float_switch_override_focus.set_selected(current_idx_float_switch_override_focus)
        dropdown_float_switch_override_focus.set_valign(Gtk.Align.CENTER)
        dropdown_float_switch_override_focus.connect("notify::selected", lambda d, _, o=FLOAT_SWITCH_OVERRIDE_OPTIONS, k='float_switch_override_focus': self._update(k, o[d.get_selected()][1]))
        row_float_switch_override_focus.add_suffix(dropdown_float_switch_override_focus)
        self.widgets['float_switch_override_focus'] = row_float_switch_override_focus
        self.widgets['float_switch_override_focus']._dropdown = dropdown_float_switch_override_focus
        self.widgets['float_switch_override_focus']._options = FLOAT_SWITCH_OVERRIDE_OPTIONS
        focus_group.add(row_float_switch_override_focus)

        content.append(focus_group)

        # === Touchpad ===
        touchpad_group = Adw.PreferencesGroup(
            title="Touchpad",
            description="Touchpad gestures, tapping and scrolling"
        )

        # Disable while typing
        row_disable_while_typing = Adw.ActionRow()
        row_disable_while_typing.set_title("Disable while typing")
        row_disable_while_typing.set_subtitle("Disables the touchpad while typing.")
        switch_disable_while_typing = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_disable_while_typing.set_active(self.settings.settings['disable_while_typing'])
        switch_disable_while_typing.connect("notify::active", lambda s, _, k='disable_while_typing': self._update(k, s.get_active()))
        row_disable_while_typing.add_suffix(switch_disable_while_typing)
        row_disable_while_typing.set_activatable_widget(switch_disable_while_typing)
        self.widgets['disable_while_typing'] = row_disable_while_typing
        self.widgets['disable_while_typing']._switch = switch_disable_while_typing
        touchpad_group.add(row_disable_while_typing)

        # Middle Button Emulation
        row_middle_button_emulation = Adw.ActionRow()
        row_middle_button_emulation.set_title("Middle Button Emulation")
        row_middle_button_emulation.set_subtitle("Allows pressing left+right buttons simultaneously to produce a middle click.")
        switch_middle_button_emulation = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_middle_button_emulation.set_active(self.settings.settings['middle_button_emulation'])
        switch_middle_button_emulation.connect("notify::active", lambda s, _, k='middle_button_emulation': self._update(k, s.get_active()))
        row_middle_button_emulation.add_suffix(switch_middle_button_emulation)
        row_middle_button_emulation.set_activatable_widget(switch_middle_button_emulation)
        self.widgets['middle_button_emulation'] = row_middle_button_emulation
        self.widgets['middle_button_emulation']._switch = switch_middle_button_emulation
        touchpad_group.add(row_middle_button_emulation)

        # Clickfinger Behavior
        row_clickfinger_behavior = Adw.ActionRow()
        row_clickfinger_behavior.set_title("Clickfinger Behavior")
        row_clickfinger_behavior.set_subtitle("Button presses with 1, 2, or 3 fingers will be mapped to LMB, RMB, and MMB respectively.")
        switch_clickfinger_behavior = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_clickfinger_behavior.set_active(self.settings.settings['clickfinger_behavior'])
        switch_clickfinger_behavior.connect("notify::active", lambda s, _, k='clickfinger_behavior': self._update(k, s.get_active()))
        row_clickfinger_behavior.add_suffix(switch_clickfinger_behavior)
        row_clickfinger_behavior.set_activatable_widget(switch_clickfinger_behavior)
        self.widgets['clickfinger_behavior'] = row_clickfinger_behavior
        self.widgets['clickfinger_behavior']._switch = switch_clickfinger_behavior
        touchpad_group.add(row_clickfinger_behavior)

        # Tap to Click
        row_tap_to_click = Adw.ActionRow()
        row_tap_to_click.set_title("Tap to Click")
        row_tap_to_click.set_subtitle("Tapping on the touchpad with 1, 2, or 3 fingers will send LMB, RMB, and MMB respectively.")
        switch_tap_to_click = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_tap_to_click.set_active(self.settings.settings['tap_to_click'])
        switch_tap_to_click.connect("notify::active", lambda s, _, k='tap_to_click': self._update(k, s.get_active()))
        row_tap_to_click.add_suffix(switch_tap_to_click)
        row_tap_to_click.set_activatable_widget(switch_tap_to_click)
        self.widgets['tap_to_click'] = row_tap_to_click
        self.widgets['tap_to_click']._switch = switch_tap_to_click
        touchpad_group.add(row_tap_to_click)

        # Drag Lock
        row_drag_lock = Adw.ActionRow()
        row_drag_lock.set_title("Drag Lock")
        row_drag_lock.set_subtitle("When enabled, lifting the finger off for a short time while dragging will not drop the dragged item.")
        string_list_drag_lock = Gtk.StringList()
        current_idx_drag_lock = 0
        for i, (label, value) in enumerate(DRAG_LOCK_OPTIONS):
            string_list_drag_lock.append(label)
            if value == self.settings.settings['drag_lock']:
                current_idx_drag_lock = i
        dropdown_drag_lock = Gtk.DropDown(model=string_list_drag_lock)
        dropdown_drag_lock.set_selected(current_idx_drag_lock)
        dropdown_drag_lock.set_valign(Gtk.Align.CENTER)
        dropdown_drag_lock.connect("notify::selected", lambda d, _, o=DRAG_LOCK_OPTIONS, k='drag_lock': self._update(k, o[d.get_selected()][1]))
        row_drag_lock.add_suffix(dropdown_drag_lock)
        self.widgets['drag_lock'] = row_drag_lock
        self.widgets['drag_lock']._dropdown = dropdown_drag_lock
        self.widgets['drag_lock']._options = DRAG_LOCK_OPTIONS
        touchpad_group.add(row_drag_lock)

        # Tap and Drag
        row_tap_and_drag = Adw.ActionRow()
        row_tap_and_drag.set_title("Tap and Drag")
        row_tap_and_drag.set_subtitle("Enables tap-and-drag gesture.")
        switch_tap_and_drag = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_tap_and_drag.set_active(self.settings.settings['tap_and_drag'])
        switch_tap_and_drag.connect("notify::active", lambda s, _, k='tap_and_drag': self._update(k, s.get_active()))
        row_tap_and_drag.add_suffix(switch_tap_and_drag)
        row_tap_and_drag.set_activatable_widget(switch_tap_and_drag)
        self.widgets['tap_and_drag'] = row_tap_and_drag
        self.widgets['tap_and_drag']._switch = switch_tap_and_drag
        touchpad_group.add(row_tap_and_drag)

        # Flip X Axis
        row_flip_x = Adw.ActionRow()
        row_flip_x.set_title("Flip X Axis")
        row_flip_x.set_subtitle("Inverts the X axis of the touchpad.")
        switch_flip_x = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_flip_x.set_active(self.settings.settings['flip_x'])
        switch_flip_x.connect("notify::active", lambda s, _, k='flip_x': self._update(k, s.get_active()))
        row_flip_x.add_suffix(switch_flip_x)
        row_flip_x.set_activatable_widget(switch_flip_x)
        self.widgets['flip_x'] = row_flip_x
        self.widgets['flip_x']._switch = switch_flip_x
        touchpad_group.add(row_flip_x)

        # Flip Y Axis
        row_flip_y = Adw.ActionRow()
        row_flip_y.set_title("Flip Y Axis")
        row_flip_y.set_subtitle("Inverts the Y axis of the touchpad.")
        switch_flip_y = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_flip_y.set_active(self.settings.settings['flip_y'])
        switch_flip_y.connect("notify::active", lambda s, _, k='flip_y': self._update(k, s.get_active()))
        row_flip_y.add_suffix(switch_flip_y)
        row_flip_y.set_activatable_widget(switch_flip_y)
        self.widgets['flip_y'] = row_flip_y
        self.widgets['flip_y']._switch = switch_flip_y
        touchpad_group.add(row_flip_y)

        # 3-Finger Drag
        row_drag_3fg = Adw.ActionRow()
        row_drag_3fg.set_title("3-Finger Drag")
        row_drag_3fg.set_subtitle("Enables 3-finger swipe to drag windows.")
        string_list_drag_3fg = Gtk.StringList()
        current_idx_drag_3fg = 0
        for i, (label, value) in enumerate(DRAG_3FG_OPTIONS):
            string_list_drag_3fg.append(label)
            if value == self.settings.settings['drag_3fg']:
                current_idx_drag_3fg = i
        dropdown_drag_3fg = Gtk.DropDown(model=string_list_drag_3fg)
        dropdown_drag_3fg.set_selected(current_idx_drag_3fg)
        dropdown_drag_3fg.set_valign(Gtk.Align.CENTER)
        dropdown_drag_3fg.connect("notify::selected", lambda d, _, o=DRAG_3FG_OPTIONS, k='drag_3fg': self._update(k, o[d.get_selected()][1]))
        row_drag_3fg.add_suffix(dropdown_drag_3fg)
        self.widgets['drag_3fg'] = row_drag_3fg
        self.widgets['drag_3fg']._dropdown = dropdown_drag_3fg
        self.widgets['drag_3fg']._options = DRAG_3FG_OPTIONS
        touchpad_group.add(row_drag_3fg)

        # Tap button mapping - Single Checklist
        checklist_group_tap_button_map = Adw.PreferencesGroup()
        checklist_group_tap_button_map.set_title("Tap Button Mapping")
        checklist_group_tap_button_map.set_description("Sets the tap button mapping for touchpad button emulation")
        self.checklist_checkbuttons['tap_button_map'] = []
        current_val = self.settings.settings['tap_button_map']
        for label, value in TAP_BUTTON_MAP_OPTIONS:
            row = Adw.ActionRow()
            row.set_title(label)
            check = Gtk.CheckButton()
            check.set_active(value == current_val)
            check.connect("toggled", self._on_checklist_single_toggle, 'tap_button_map', value)
            row.add_prefix(check)
            row.set_activatable_widget(check)
            checklist_group_tap_button_map.add(row)
            self.checklist_checkbuttons['tap_button_map'].append((check, value))
        touchpad_group.add(checklist_group_tap_button_map)

        content.append(touchpad_group)

        # === Virtual Keyboard ===
        virtualkeyboard_group = Adw.PreferencesGroup(
            title="Virtual Keyboard",
            description="Virtual keyboard state sharing and behavior"
        )

        # Share States
        row_share_states = Adw.ActionRow()
        row_share_states.set_title("Share States")
        row_share_states.set_subtitle("Unify key down states and modifier states with other keyboards")
        string_list_share_states = Gtk.StringList()
        current_idx_share_states = 0
        for i, (label, value) in enumerate(SHARE_STATES_OPTIONS):
            string_list_share_states.append(label)
            if value == self.settings.settings['share_states']:
                current_idx_share_states = i
        dropdown_share_states = Gtk.DropDown(model=string_list_share_states)
        dropdown_share_states.set_selected(current_idx_share_states)
        dropdown_share_states.set_valign(Gtk.Align.CENTER)
        dropdown_share_states.connect("notify::selected", lambda d, _, o=SHARE_STATES_OPTIONS, k='share_states': self._update(k, o[d.get_selected()][1]))
        row_share_states.add_suffix(dropdown_share_states)
        self.widgets['share_states'] = row_share_states
        self.widgets['share_states']._dropdown = dropdown_share_states
        self.widgets['share_states']._options = SHARE_STATES_OPTIONS
        virtualkeyboard_group.add(row_share_states)

        # Release all Pressed Keys by Virtual Keyboard on Close.
        row_release_pressed_on_close = Adw.ActionRow()
        row_release_pressed_on_close.set_title("Release all Pressed Keys by Virtual Keyboard on Close.")
        switch_release_pressed_on_close = Gtk.Switch(valign=Gtk.Align.CENTER)
        switch_release_pressed_on_close.set_active(self.settings.settings['release_pressed_on_close'])
        switch_release_pressed_on_close.connect("notify::active", lambda s, _, k='release_pressed_on_close': self._update(k, s.get_active()))
        row_release_pressed_on_close.add_suffix(switch_release_pressed_on_close)
        row_release_pressed_on_close.set_activatable_widget(switch_release_pressed_on_close)
        self.widgets['release_pressed_on_close'] = row_release_pressed_on_close
        self.widgets['release_pressed_on_close']._switch = switch_release_pressed_on_close
        virtualkeyboard_group.add(row_release_pressed_on_close)

        content.append(virtualkeyboard_group)

        # === Touchdevice ===
        touchdevice_group = Adw.PreferencesGroup(
            title="Touch Device",
            description="Touchscreen transform and monitor binding"
        )

        # Transform the input from touchdevices.
        row_transform = Adw.ActionRow()
        row_transform.set_title("Transform the input from touchdevices.")
        string_list_transform = Gtk.StringList()
        current_idx_transform = 0
        for i, (label, value) in enumerate(TRANSFORM_OPTIONS):
            string_list_transform.append(label)
            if value == self.settings.settings['transform']:
                current_idx_transform = i
        dropdown_transform = Gtk.DropDown(model=string_list_transform)
        dropdown_transform.set_selected(current_idx_transform)
        dropdown_transform.set_valign(Gtk.Align.CENTER)
        dropdown_transform.connect("notify::selected", lambda d, _, o=TRANSFORM_OPTIONS, k='transform': self._update(k, o[d.get_selected()][1]))
        row_transform.add_suffix(dropdown_transform)
        self.widgets['transform'] = row_transform
        self.widgets['transform']._dropdown = dropdown_transform
        self.widgets['transform']._options = TRANSFORM_OPTIONS
        touchdevice_group.add(row_transform)

        # The monitor to bind touch devices. The default is auto-detection.
        row_output = Adw.ActionRow()
        row_output.set_title("The monitor to bind touch devices. The default is auto-detection.")
        row_output.set_subtitle("Specify your monitor to bind to touch device")
        entry_output = Gtk.Entry()
        entry_output.set_text(str(self.settings.settings['output']))
        entry_output.set_valign(Gtk.Align.CENTER)
        entry_output.set_size_request(200, -1)
        entry_output.connect("changed", lambda e, k='output': self._update(k, e.get_text()))
        row_output.add_suffix(entry_output)
        self.widgets['output'] = row_output
        self.widgets['output']._entry = entry_output
        touchdevice_group.add(row_output)

        content.append(touchdevice_group)

        scrolled.set_child(content)
        main_box.append(scrolled)
        main_box.append(self.status_bar)
        
        self.set_content(main_box)
        self._update_conditionals()
    
    def _update(self, key, value):
        self.settings.settings[key] = value
        self.status_bar.set_text(f"Changed: {key}")
        self._update_conditionals()
    
    def on_apply(self, button):
        if self.settings.save_config():
            self.status_bar.set_text("✓ Saved successfully!")
        else:
            self.status_bar.set_text("✗ Error saving - check permissions")
    
    def on_reset(self, button):
        self.settings.reset_to_defaults()
        self._refresh_all()
        self.status_bar.set_text("Reset to defaults")
    
    def _refresh_all(self):
        for key, widget in self.widgets.items():
            val = self.settings.settings.get(key)
            if hasattr(widget, '_scale'):
                widget._scale.get_adjustment().set_value(val)
            elif hasattr(widget, '_switch'):
                widget._switch.set_active(val)
            elif hasattr(widget, '_dropdown'):
                if hasattr(widget, '_options'):
                    for i, (_, v) in enumerate(widget._options):
                        if v == val:
                            widget._dropdown.set_selected(i)
                            break
            elif hasattr(widget, '_entry'):
                widget._entry.set_text(str(val))
        # Update checklist checkbuttons
        for key, checkbuttons in self.checklist_checkbuttons.items():
            val = self.settings.settings.get(key)
            if isinstance(val, list):
                for cb, v in checkbuttons:
                    cb.set_active(v in val)
            else:
                for cb, v in checkbuttons:
                    cb.set_active(v == val)
        self._update_conditionals()
    
    def _update_conditionals(self):
        if 'follow_mouse_threshold' in self.widgets:
            cond_val = self.settings.settings.get('follow_mouse')
            if isinstance(cond_val, bool):
                show = str(cond_val).lower() == '1'
            else:
                show = str(cond_val) == '1'
            self.widgets['follow_mouse_threshold'].set_visible(show)
        if 'mouse_refocus' in self.widgets:
            cond_val = self.settings.settings.get('follow_mouse')
            if isinstance(cond_val, bool):
                show = str(cond_val).lower() == '1'
            else:
                show = str(cond_val) == '1'
            self.widgets['mouse_refocus'].set_visible(show)
        
    def _on_checklist_single_toggle(self, button, key, value):
        if button.get_active():
            if key in self.checklist_checkbuttons:
                for cb, val in self.checklist_checkbuttons[key]:
                    if cb != button:
                        cb.set_active(False)
            self._update(key, value)
    
    def _on_checklist_multi_toggle(self, button, key, value):
        if key not in self.checklist_checkbuttons:
            return
        selected = [val for cb, val in self.checklist_checkbuttons[key] if cb.get_active()]
        self._update(key, selected)



# APPLICATION


class Application(Adw.Application):
    def __init__(self):
        super().__init__(application_id='com.Nordix.Settings.Input', flags=Gio.ApplicationFlags.FLAGS_NONE)
    
    def do_activate(self):
        win = MainWindow(self)
        win.present()


def main():
    app = Application()
    return app.run(None)


if __name__ == "__main__":
    main()
