#====================================================================================================#
#                                        Nordix MPV Config                                           #
#====================================================================================================#
hwdec=auto-safe  # Enables hardware decoding. You can also use specific APIs like vaapi, nvdec, or vulkan.
vo=gpu           # Uses GPU for video output (necessary for hardware acceleration).
profile=gpu-hq
gpu-api=vulkan   
vd-lavc-dr=yes   # Enables Direct Rendering to reduce copying between CPU and GPU.
panscan=1.0
loop-file=inf    # restart video


#=====================================================================================================#

cscale=ewa_lanczossharp  # This means that the colors are also scaled with the same high sharpness as the brightness (luma), which makes the image even a little more "solid".

dscale=mitchell          # Used when scaling down a video (e.g. 4K video on 1080p display) to retain detail.
 sharpen=0.5             # A simple filter. Try a low value like 0.5 to 1.0. Too high values look unnatural.
# scale-blur=<värde>     # By setting a negative value (e.g. -0.5 to -1.0) with some scalers (like lanczos) you increase the perceived sharpness, so-called
# interpolation=yes      # Reduces "jidder" and motion blur when panning.
# tscale=oversample      # An interpolation algorithm that maintains sharpness in each frame but makes motion smoother.
 
audio-device=auto     # Ensures that the sound always finds the correct output.
volume=100            # Default volume.
audio-channels=auto   # Standard volume Handles everything from stereo to surround.
ao=pipewire           # (Or pulse) For efficient sound management

#=====================================================================================================#
# scale=vulkan scale=split or scale=vulkan: Often gives much sharper results than standard (bilinear).
scale=ewa_lanczossharp     # The most popular algorithm for high sharpness without too much artifacts.

#=====================================================================================================#