


# colors som finns i source = ~/.config/hypr/config/colors.conf
# 'p' stands for pure, 'i' for ice, t stands for transparent
$nordix-pblack = rgba(000000ff) # - Pure-Black
$nordix-tpblack = rgba(000000aa) # - Transparent Pure-Black
$nordix-pred = rgba(ff0000ff) # - Pure-Red
$nordix-tpred = rgba(ff0000aa) # - transparent Pure-Red
$nordix-ppink =  rgba(eb4899ff) # - Pure-Pink
$nordix-tpink =  rgba(eb4899aa) # - Transparent Pure-Pink
$nordix-pwhite = rgba(ffffffff) # - Pure-White
$nordix-tpwhite = rgba(ffffffaa) # - Trasnparent Pure-White
$nordix-pblue = rgba(01ccffff) # - Pure-Blue
$nordix-tpblue = rgba(01ccffaa) # - Transparent Pure-Blue
$nordix-blue = rgba(13abc6ff) # - Blue
$nordix-tblue = rgba(13abc6aa) # - Transparent Blue 
$nordix-ice = rgba(0084afff) # - Ice     
$nordix-tice = rgba(0084afaa) # - Transparent Ice     
$nordix-artic = rgba(9ce6ffff) # - Artic 
$nordix-tartic = rgba(9ce6ffaa) # - Transparent Artic 
$nordix-glacier = rgba(50c8ffff) # - Glacier 
$nordix-tglacier = rgba(50c8ffaa) # - Transparent Glacier  
$nordix-frost = rgba(d2ffffff) # - Frost  
$nordix-tfrost = rgba(d2ffffaa) # - Transparent Frost  
$nordix-hyprblue = rgba(00d2ffff) # - Hyprblue
$nordix-thyprblue = rgba(00d2ffaa) # - Transparent Hyprblue
$nordix-green = rgba(00ff00ff) # - Green
$nordix-tgreen = rgba(00ff00aa) # - Transparent Green
$nordix-mint = rgba(00aa86ff) # - Mint
$nordix-tmint = rgba(00aa86aa) # - Transparent Mint
$nordix-violet = rgba(998cc9ff) # - Violet
$nordix-tviolet = rgba(998cc9aa) # - Transparent Violet
$nordix-ghost = rgba(aabaaeff) # - Ghost
$nordix-tghost = rgba(aabaaeaa) # - Transparent Ghost
$nordix-mustard = rgba(a1b116ff) # - Muatard
$nordix-tmustard = rgba(a1b116ba) # - Transparent Mustard
$nordix-iblue = rgba(affbfdff) # - Ice-Blue
$nordix-tvblue = rgba(affbfdaa) # - Transparent Ice-Blue
$nordix-forest = rgba(4AC283ff) # - Forest 
$nordix-tforest = rgba(4AC283aa) # - Transparent Forest
$nordix-fish = rgba(8a9685ff) # - Fish
$nordix-tfish = rgba(8a9685aa) # - Transparent Fish
$nordix-arora = rgba(6c63ffff) # - Arora
$nordix-tarora = rgba(6c63ffaa) # - Transparent Arora
$nordix-retro = rgba(17d67bff) # - Retro-Green
$nordix-tretro = rgba(17d67baa) # - Transparent Retro-Green
$nordix-studio = rgba(9856C4ff) # - Studio 
$nordix-tstudio = rgba(9856C4aa) # - Transparent Studio
$nordix-babyblue = rgba(73CFFFff) # - Baby-Blue
$nordix-tbabyblue = rgba(73CFFFaa) # - Transparent Baby-Blue

 ###################                         ########################
 # Greay scale: 1: 100% opak, 2: 67% opak, 3: 50% opak, 4: 0% opak # 
#########                            ##############################

$nordix-slategray-1  = rgba(5E686Dff)
$nordix-slategray-2  = rgba(5E686Daa)
$nordix-slategray-3  = rgba(5E686D80)
$nordix-slategray-4  = rgba(5E686D00)

$nordix-steelgray-1 = rgba(545E63ff)
$nordix-steelgray-2 = rgba(545E63aa)
$nordix-steelgray-3 = rgba(545E6380)
$nordix-steelgray-4 = rgba(545E6300)

$nordix-darksteel-1 = rgba(404A4Fff)
$nordix-darksteel-2 = rgba(404A4Faa)
$nordix-darksteel-3 = rgba(404A4F80)
$nordix-darksteel-4 = rgba(404A4F00)

$nordix-charcoalgray-1 = rgba(363F44ff)
$nordix-charcoalgray-2 = rgba(363F44aa)
$nordix-charcoalgray-3 = rgba(363F4480)
$nordix-charcoalgray-4 = rgba(363F4400)




# New colcor






$nordix-glacier-blue = #4aa3ff

$frost-crystal = #8fcbff

#winter-aurora = #6ad4b2

#nordic-mist = #2b7af0

#base = #b3f0ff  #crystal-ice  