##===============================================================##
 #                          Yggdrasil's                          # 
 #                    Hyprland Configurations                    #
##===============================================================##
 #  * Copyright (c) 2025 Jimmy Källhagen                         #
 #  * Part of Yggdrasil - Nordix desktop environment             #
##===============================================================##

##=======================##
 #     Source Files      #
##=======================##
## Nordix - Default apps
source = ~/.config/nordix/yggdrasil/settings/nordix-defaults.conf

### System's - WindowRules ###
source = /usr/share/nordix/yggdrasil/config/system-windowrules.conf

### Color and Default Apps ###
source = ~/.config/nordix/yggdrasil/color/colors.conf

##=======================##
 #         Desktop       #
##=======================##
### Destop Envirorment, Keybinds and Monitors ###
source = ~/.config/nordix/yggdrasil/settings/nordix-environment.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-monitors.conf
source = ~/.config/nordix/yggdrasil/keybinds/nordix-keybinds.conf

### Animations and Decorations ###
source = ~/.config/nordix/yggdrasil/animations/nordix-animations.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-decorations.conf

### Yggdrasil's Hyprland Settings ###
source = ~/.config/nordix/yggdrasil/settings/nordix-advanced.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-general.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-groups.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-input.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-binds.conf
source = ~/.config/nordix/yggdrasil/settings/nordix-layout.conf

### Autostart Apps in ~/.config/autostart ###
source = /usr/share/nordix/yggdrasil/config/nordix-autostart.conf

### User's WindowsRules ###
source = ~/.config/nordix/yggdrasil/windowsrules/user-windowrules.conf

#===========================================================#
#                 Xwayland Scaling=off                      # 
#===========================================================#
# It is better o toggle scaling on when you need it.        #
#                                                           #
# * Steam, lutris and Heroic                                #
#   vill start the game with wrong resulotion               #
#   if you dont have scaling of                             #
#                                                           #
# * Toggle Xwayland Scaling With: (SUPER + X)               #
#===========================================================#
 xwayland {
   force_zero_scaling = false       # Unscale XWayland
 }

debug {
    damage_tracking = 0
}
#source = /usr/share/nordix/yggdrasil/floating-mode/floating.conf
